### ISSUE TITLE
User configurable baud rates

### ISSUE THREAD

**Issue by BoomBoxHPB** [microsoft/vscode-serial-monitor#1]
Type: Feature Request

The hardcoded list of baud rates is a good start, but I've already found a number of projects that utilize higher baud rates than the list supports currently (ex 921600 or even 3MBaud). Rather than try to account for every possible baud rate in the hardcoded list, could a user supply a custom baud rate either directly or via a user setting to provide a custom list?

For example:
`"serial-monitor.baudRates": [
        115200,
        921600,
        3000000
    ],
`

**Comment by benmcmorran** [comment]
Great suggestion! I'm marking this as a feature request, and I expect we'll be able to add this functionality in the next release.

Out of curiosity, what devices or projects are you working with that use these high baud rates? If we can reproduce your setup, we'll be better able to test the functionality before release.

**Comment by BoomBoxHPB** [comment]
They're embedded devices (Cortex-M4/M33) that utilize an FTDI chip to translate from UART to a virtual COM port over USB. Our main use case is debug printf's on pre-production hardware, although if you give a developer a tool it's ripe for abuse. 😁

**Comment by gcampbell-msft** [comment]
Hi, @BoomBoxHPB! I wanted to let you know that we now have support for setting additional settings like Data bits, stop bits, and parity, as well as logging to a file, available in the **pre-release channel**. We haven't gotten around to custom baud rates (the feature you requested), but I wanted to give an update about our other features and let you know that it is in the backlog!

**Comment by hongshui3000** [comment]
Works

**Comment by xiaguangbo** [comment]
@gcampbell-msft  The serial ports of my "rock pi s" and "firefly rk3399" development boards are both 1.5Mbps, I really need this function. It would be better if it could replace "putty", "mobaxterm", "xshell"...

**Comment by gcampbell-msft** [comment]
Please check out the new release!
