### ISSUE TITLE
Use `var(--vscode-editor-font-family)` in the output window

### ISSUE THREAD

**Issue by trond-snekvik** [microsoft/vscode-serial-monitor#10]
Type: Feature Request

On Linux, Consolas isn't available, and the output font defaults to a non-monospace serif, which isn't particularly readable.

Please consider using `var(--vscode-editor-font-family)`, either as the primary font family, or as a fallback after Consolas, so we can get the same font in the monitor as the editor.

**Comment by gcampbell-msft** [comment]
Hi @trond-snekvik, while we don't currently have an estimated date for the next release. There is a fix in for this issue that will be visible on next release. Thanks for your feedback!
