### ISSUE TITLE
Large delay or slow output (increases over time)

### ISSUE THREAD

**Issue by MrTucks** [microsoft/vscode-serial-monitor#101]
Type: Bug Report

**Describe the bug**
- OS and Version: Win11 Home 22H2
- VS Code Version: 11.77.3 as well as 11.78.0
- Serial Monitor Extension Version: 0.9.0 as well as v0.9.230504001
- Target embedded device: Raspberry Pi Pico W - RP2040 - Earlephilhower arduino-pico core
- Other extensions you installed (and if the issue persists after disabling them): disabled all extensions except vscode-language-pack-de 
and the issue still persists.
Installed: MS-CEINTL.vscode-language-pack-de ms-vscode.vscode-serial-monitor jeff-hykin.better-cpp-syntax alefragnani.Bookmarks ms-vscode.cpptools ms-vscode.cpptools-extension-pack ms-vscode.cpptools-themes twxs.cmake ms-vscode.cmake-tools streetsidesoftware.code-spell-checker ms-vscode-remote.remote-containers cschlosser.doxdocgen file-icons.file-icons streetsidesoftware.code-spell-checker-german donjayamanne.githistory codezombiech.gitignore eamodio.gitlens ms-toolsai.jupyter ms-toolsai.vscode-jupyter-cell-tags ms-toolsai.jupyter-keymap ms-toolsai.jupyter-renderers ms-toolsai.vscode-jupyter-slideshow monokai.theme-monokai-pro-vscode IBM.output-colorizer platformio.platformio-ide alefragnani.project-manager ms-python.vscode-pylance ms-python.python ms-vscode-remote.remote-ssh ms-vscode-remote.remote-ssh-edit ms-vscode.remote-explorer dqisme.sync-scroll enkia.tokyo-night tomoki1207.pdf ms-vscode-remote.remote-wsl
- A clear and concise description of what the bug is.

**To Reproduce**
1. Have a program on the Pi pico, that quickly and continuously sends a lot of text data to the USB serial port. I noticed this bug with the logging functionality of an audio library. According to the timestamps of this serial monitor, it sends about 3 lines of about 80 characters each per millisecond.
2. Enable timestamps and autoscroll in the serial monitor. This isn't required to reproduce the bug itself, but it makes the bug more obvious to notice.
4. Plug in the Pico and start monitoring
5. The timestamps in the serial monitor show the current time. New lines of text appear suspiciously slowly.
6. wait a while.
7. The difference between timestamp and actual time grows. For example, after 5 minutes of serial monitoring, the timestamps read 21:48, but the current time is 21:50. The serial monitor has a delay of about 2 minutes. 
8. Unplug the pico. While the serial monitor immediately detects that the port is disconnected, new text continues to appear for multiple minutes. (The longer the serial monitor was running, the higher the delay. And with a higher delay, new lines will continue to appear for longer.) 

**Expected behavior**
Text appears immediately after it's received.
In step 5: new lines appear quicker than you can possibly read them
In step 7: the timestamps always show the current time. The monitor should always display input as soon as it is received.
In step 8: Output stops immediately after disconnecting the pico.

Platformio also has a serial monitor, which uses a terminal. Using it (or another serial monitor software) instead of this extension, I get the expected behaviour. 
The lines appear noticeably faster. When I unplug the pico, new lines immediately stop to appear.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/41760293/236314894-7f44da0b-364e-4d94-abf3-cc575628f16e.png)
![grafik](https://user-images.githubusercontent.com/41760293/236322951-b25c60dd-6ad0-4759-84c5-155aead79cdf.png)

I know there are already other issues about delay. But they're closed as fixed. So maybe this is another issue or the delay issue isn't completely fixed.

**Comment by MrTucks** [comment]
Hi, thanks for looking into this.

The audio library that first made me notice this is single threaded and sends mostly 2, sometimes 1 or 3 lines per millisecond, according to the timestamps of this serial monitor.
It sends one log message every time it completes one loop of:
Read a few bytes from program memory.
Do a little bit of copying.
Send them out to the audio buffer, if it's full, immediately try again.
Basically, really fast!

1ms of delay between lines is already enough to stop this problem. 

Here is the minimum sketch to reproduce the problem on a Raspberry Pi Pico W (probably the same on the non-W):
```cpp
#include <Arduino.h>
void setup() {
  Serial.begin(115200);
}

void loop() {
  int i = 0;
  while(true){
    delay(1);
    Serial.print("Hello, this is seventy characters of text with the i inc. at the end :");
    Serial.println(i++);
  }
}
```
and platformio.ini:
```
[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
```

With the delay(1) the problem doesn't occur.

Removing the delay(1):
The problem occurs and is noticeable pretty quickly.
Reproduction Step 7 is already very noticeable after only one minute of serial monitoring. After unplugging the pico, new lines continue to appear for more than 3 minutes.
Reproduction Step 6 is noticeable within 5 minutes.
Even though this sketch hits the serial port as fast as possible, the serial monitor from the PlatformIO VS Code extension is able too keep up.
It doesn't have timestamps (so step 6 can't be compared). But after unplugging the pico, it stops immediately. 
And, on the PlatformIO serial monitor, the last 3 digits are completely unreadable because it scrolls past so fast.
But on this serial monitor, text appears slowly enough that all digits are readable. So this serial monitor is definitely slower.
Sorry for not including this minimum reproduction sketch in my first post.

Just for fun:
CPU Usage of VS code according to task manager:
This extensions serial monitor: 15-20%
Platformio serial monitor: about 50%



And sorry, I have never used typescript, javascript or nodejs.
I put the script into a new file called test.ts.
In the terminal, I did:
`npm init`.
`npm install serialport`
`Node test.ts`
and I get this error:
```
const serialPort: SerialPort = new SerialPort({path: "COM4", baudRate: 115200, dataBits: 8, stopBits: 1, parity: "none", autoOpen: false});
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
```

**Comment by gcampbell-msft** [comment]
@MrTucks No worries! I will use your minimum sketch to see if I can reproduce. I don't currently have the exact hardware on hand, but I will attempt to reproduce with the hardware that I do have. Thanks for the in depth information as it makes it a lot easier to attempt to repro. 

Thanks!

**Comment by gcampbell-msft** [comment]
@MrTucks I've investigated further and am still not able to reproduce. Here's the steps that I took

1. I copied the code from your repro sketch, and uploaded it to my hardware (Arduino Mega2560) (with the delay commented out to attempt to reproduce the issue)
2. Started monitoring

I then did two tests, I first let it run for 3-4 minutes and then unplugged the board. I was not able to reproduce the extra output, as the Serial Monitor stopped outputting data within seconds (maybe milliseconds). 

I also tested letting it run for awhile to see if the timestamps got out of sync with the current time. I ran the Serial Monitor for up to 13 minutes, and even after that, the timestamps were still in sync with the current time. 

Is there any other information that I should know that can help us resolve your issue?

**Comment by MrTucks** [comment]
Are you receiving 3 or more lines per millisecond (according to the timestamps) with the Arduino Mega?
Hmm, I'm sorry, I don't really have other ideas.
I will try on a second PC when I have time. But I hope it's ok, that this might be in a week or more because I don't have much time right now.

**Comment by MrTucks** [comment]
Btw, I have a Ryzen 5 2600. Maybe it's limited by my CPU and your PC is faster (or faster on a single core). 15-20% CPU usage could roughly be 100% usage on a single core. This is just an idea and I have done nothing to test it.
Thanks again for looking into it.

**Comment by gcampbell-msft** [comment]
@MrTucks Have you been able to reproduce this on another machine? Thanks for helping us investigate.

**Comment by MrTucks** [comment]
Sorry.
I just reproduced it on my Lenovo IdeaPad 5 Pro-14ACN (while plugged in) with:
Ryzen 7 5800U
Windows 11 Pro 22H2
and VS Code 1.80 and serial monitor extension v0.10.230713001
