### ISSUE TITLE
Add font setting

### ISSUE THREAD

**Issue by RodMe27** [microsoft/vscode-serial-monitor#106]
Type: Feature Request

 It would be nice to have a font selector.

**Comment by gcampbell-msft** [comment]
Our font is based on the editor font setting that has a setting ID of `editor.fontFamily`. You should be able to use this and modify the font!

Thanks! Closing the issue for now, but please re-open, or open another issue, if this doesn't meet your needs.

**Comment by Eplankton** [comment]
> Our font is based on the editor font setting that has a setting ID of `editor.fontFamily`. You should be able to use this and modify the font!
> 
> Thanks! Closing the issue for now, but please re-open, or open another issue, if this doesn't meet your needs.

I think we should have some settings that independent from vscode editor.fontFamily, maybe a different font in serial monitor.

**Comment by raffaeler** [comment]
I second this. On Ubuntu 24.04, I can't see the underscore character in the Serial Monitor.
Here the screenshot difference between the editor and the Serial Monitor:

![Image](https://github.com/user-attachments/assets/0fb985a3-6b6e-4a76-8bc2-369ff49c3919)
