### ISSUE TITLE
Not support serial controller CH340  while CP210x works well, I have verified both on ESP8266 and ESP32 develoment board

### ISSUE THREAD

**Issue by qiumanliang** [microsoft/vscode-serial-monitor#107]
Type: Bug Report

**Describe the bug**
- OS and Version:
- VS Code Version:
- Serial Monitor Extension Version:
- Target embedded device:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Code sample and logs**
- Code sample
- `launch.json`

**Screenshots**

**Additional context**

**Comment by itodirel** [comment]
@qiumanliang can you give us more context and repro steps?

**Comment by qiumanliang** [comment]
![image](https://github.com/microsoft/vscode-serial-monitor/assets/98149963/2909cef8-10a5-4a59-a6fc-1f74ac6d7d55)
It was fixed when I change different USB cable. thanks for your kind response.
