### ISSUE TITLE
Correct port is not being opened

### ISSUE THREAD

**Issue by rossb93** [microsoft/vscode-serial-monitor#109]
Type: Bug Report

**Describe the bug**
- OS: Windows 10 Enterprise
- VS Code Version: 1.78.2
- Serial Monitor Extension Version: v0.9.230531001

The selected COM port in the Port drop down is not being opened. 

**To Reproduce**
1. Have serial monitor open
2. See a COM port in the Port select dropdown
3. Connect a new USB device to the PC
4. Refresh the COM ports
5. Select the newly found COM port
6. Click start monitoring
7. See it opens the serial port originally seen in the port select dropdown and not the newly selected com port

Work arounds:
1. If I close and reopen VSCode and then try to connect to the new comport (without disconnecting the USB device) it then opens the correct COM port.
2. If I press start monitoring on the old com port, then select the new com port in the drop down then press start monitoring. It opens the new COM port correctly

**Expected behavior**
1. Serial monitor correctly connects to the selected COM port

**Screenshots**
1. Without new com port:
![image](https://github.com/microsoft/vscode-serial-monitor/assets/6604082/3fce00a1-f079-481b-b90a-f70c21ca20ff)

3. New usb device connected, port dropdown refreshed and new com port selected
![image](https://github.com/microsoft/vscode-serial-monitor/assets/6604082/60902719-2477-4e05-ba6e-65910e487048)

4. Old com port in view is opened after pressing the start monitoring button and not the selected one:
![image](https://github.com/microsoft/vscode-serial-monitor/assets/6604082/b32060cd-91a9-418d-89cb-e61ea129b7bb)

**Additional context**
Where I say to connect a new USB device I am using virtualHere to select a com port to open.

**Comment by gcampbell-msft** [comment]
@rossb93 I attempted to reproduce this issue and was not able to. Could you provide some more information about what your steps were? 

Did you hit refresh, then select the new port, and then try to start monitoring? Was a new port automatically selected when you pressed refresh? Any information, or even better, a gif/video of the bug being reproduced, would be fantastic!

Thanks!

**Comment by rossb93** [comment]
I find this issue is intermittent so not so easy to reproduce. Next time I see an occurrence of it I will try to screen record the repro steps.

As for your questions on my above repro steps:
**Did you hit refresh, then select the new port, and then try to start monitoring?**
_Yes the steps were hit refresh, select the new port, and then select Start Monitoring. At which point it opens a connection with the previously selected COM port instead of the newly selected one_

**Was a new port automatically selected when you pressed refresh?** 
_No the new port wasn't automatically selected, since the previous port still exists that port remained selected. It was only following a refresh and manually selecting the new port from the dropdown that the new port became selected_

**Comment by rossb93** [comment]
I still keep seeing this bug. I can't think of a way to record/gif the bug, but the screenshots above show (specifically screenshot 3) that after pressing Start Monitoring on the selected COM port it opens the serial port for a different COM port that the one selected in the dropdown (opens COM9 instead of COM13). I'm surprised no one else has encountered this bug

**Comment by Ahmed1893** [comment]
i get the same message on ubuntu 23.04 (Jammy Jellyfish) and vscode 1.81.1 and arduino v0.6.0 
![Screenshot from 2023-08-20 20-45-17](https://github.com/microsoft/vscode-serial-monitor/assets/77455176/e5146fae-bdff-4feb-8182-9a225ba05bbf)

**Comment by gcampbell-msft** [comment]
@Ahmed1893 I think your screenshot may be a different issue. Do you have file logging enabled? I've hit this where I had file logging enabled and the directory I wanted to log to no longer exists on my system and it causes issues opening the port, because it fails to open the file. Could this be your situation?

**Comment by gcampbell-msft** [comment]
@Ahmed1893 I just attempted to repro your original issue, and it doesn't seem to reproduce, could you confirm? 

Thanks.
