### ISSUE TITLE
Serial Monitor Zephyr does not interpret escape codes.

### ISSUE THREAD

**Issue by paveldedourek-eaton** [microsoft/vscode-serial-monitor#11]
I would like to mentioned, that it is expected by Zephyr that this console support escape codes but in implementation does not. 

![image](https://user-images.githubusercontent.com/98147995/173297611-e84a5024-4152-4eea-b9fd-ac21ba5aefad.png)

`m

[1;3232muart:~$0m<dbg> ADE9078: ade9[J[00:00:t:~$ [m[ [0m<inf>0:02.913,0
`

https://docs.zephyrproject.org/latest/services/shell/index.html
`Support for ANSI escape codes: VT100 and ESC[n~ for cursor control and color printing.`

**Comment by hongshui3000** [comment]
Similar to my issue :https://github.com/microsoft/vscode-serial-monitor/issues/4

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking with #46

**Comment by gcampbell-msft** [comment]
@paveldedourek-eaton Hi! We now have implemented support for these escape codes and it is available for testing out in the current pre-release version of the serial monitor. 

Please feel free to test it out and let us know if it works for you!
