### ISSUE TITLE
script processing data

### ISSUE THREAD

**Issue by Antecer** [microsoft/vscode-serial-monitor#118]
I would like to be able to use JavaScript to do custom processing of received data, or use Javascript to automatically manage sent data.

This will greatly improve the user experience, people can edit the script to achieve the function.

**Comment by hongshui3000** [comment]
https://github.com/microsoft/vscode-serial-monitor/issues/74
Basically the same as my needs

**Comment by Antecer** [comment]
yeah, i think javascript will better than vb.

**Comment by hongshui3000** [comment]
I agree, TS/JS is the better choice

**Comment by Antecer** [comment]
I think the functionality can refer to this tool, the only problem is that it uses Lua:
[LLCOM](https://llcom.papapoi.com/)

I still prefer a markup language like C language.
Programming languages without curly braces confuse me.

**Comment by gcampbell-msft** [comment]
@Antecer Thanks for the request! We've got this on our backlog and will continually assess when we can complete this item. We are currently tracking this request with #74 , so I will close this request as a duplicate. Thanks!
