### ISSUE TITLE
Double New Line when press Return/Enter in terminal mode (Linux)

### ISSUE THREAD

**Issue by Ossanes** [microsoft/vscode-serial-monitor#124]
Type: Bug Report

**Double New Line when press Return**
- OS and Version: Arch Linux (Kernel 6.4.9-arch1-1)
- VS Code Version: 1.80.2
- Serial Monitor Extension Version: 0.10.0
- Target embedded device: Custom board based on National Instruments AM335x running a custom Linux image.

When I access a board through serial console, every time I press Return key acts like I pressed twice.

**To Reproduce**
1. Connect to a serial console device
2. Hit Enter/Return
3. It will act twice

**Expected behavior**
Enter should act once per pressing.

**Comment by gcampbell-msft** [comment]
@Ossanes Could you switch to the pre-release version and let me know if the issue persists? There should be a fix available there. 

Thanks!

**Comment by Ossanes** [comment]
The pre-release version fixes this issue. Thanks!
