### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by 7w1nk** [microsoft/vscode-serial-monitor#125]
How to change the output data encoding? And Is it possible to view data in hex or dec format?

**Comment by 7w1nk** [comment]
Sure, I can convert and transfer a byte with two byte halves, but that takes twice as long

**Comment by gcampbell-msft** [comment]
Marking this as a duplicate #5 . We have plans to implement this in either the next release, or the one after. Thanks!

**Comment by 7w1nk** [comment]
Ooh, My apologies! This question was brought up a year ago that I missed seeing it

**Comment by pedy** [comment]
There is use case that is different with both the _double-byte case_ Alexander mentioned and _#5_ : 
Some non-ASCII encodings use only one byte per character. For example [cp1256](https://en.wikipedia.org/wiki/Windows-1256) uses single byte for each character, but its values exceeds standard ASCII range. Some tools like [SUDT AccessPort](https://www.sudt.com/en/ap/index.html) doesn't show proper encoding in its console, but keeps the data intact in the saved output file, so I can open the log file with a text editor (e.g. Notepad++) and set the proper encoding. This is not the case in this extension; it doesn't show the proper encoding (it's like the SUDT tool in this matter), and it doesn't save proper data in the log file.

I have two requests:
1) Don't let the extension mess with non-ASCII single byte characters (Just like the mentioned freeware)
2) Feature request: Support displaying other encodings in the serial monitor console itself

![vscode-serial-monitor](https://github.com/microsoft/vscode-serial-monitor/assets/7770727/d35eea14-a5f2-413a-a5f3-ca8f13ef7e5d)
