### ISSUE TITLE
Terminal mode cannot enter characters normally

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#127]
Terminal mode cannot enter characters normally

I can’t manually enter characters and then ctrl+v to copy characters, I can only right-click and paste characters into the terminal

![image](https://github.com/microsoft/vscode-serial-monitor/assets/25566498/18f9a103-83cb-404c-9f91-87f011a11436)

![image](https://github.com/microsoft/vscode-serial-monitor/assets/25566498/dbc949ad-acdb-4f7d-9c4d-17036754299e)

**Comment by gcampbell-msft** [comment]
What version of the extension are you using and can you show a video of what you're referring to? I have just tested with the most recent version of the extension and confirmed that it is working as expected on my machine. 

Thanks!

**Comment by Luke-Guangzhong** [comment]
Same problem here. Version of the extension is v0.10.230825001.

![20230830_145014](https://github.com/microsoft/vscode-serial-monitor/assets/78730836/662b78c3-3924-44c5-91e3-3800dd04ed78)

If you need more infomation, just let me know.

Thanks!

**Comment by gcampbell-msft** [comment]
@Luke-Guangzhong @hongshui3000 Do you happen to know what version of the extension last worked for you?

**Comment by gcampbell-msft** [comment]
@Luke-Guangzhong @hongshui3000 I may have diagnosed the issue, I'm investigating now and hope to merge a fix that will go into pre-release tomorrow. Thanks for catching this quickly!

**Comment by Luke-Guangzhong** [comment]
The latest version worked for me is v0.10.0. But it has another problem. --> [Double New Line when press Return/Enter in terminal mode (Linux) · Issue #124 · microsoft/vscode-serial-monitor (github.com)](https://github.com/microsoft/vscode-serial-monitor/issues/124)

**Comment by gcampbell-msft** [comment]
@Luke-Guangzhong These issues should be fixed in the most recent release.
