### ISSUE TITLE
Logging serial monitor, characters get swopped

### ISSUE THREAD

**Issue by Chris-DV** [microsoft/vscode-serial-monitor#129]
So I was logging data from pressure sensors over RS232. The serial monitor extension (with timestamp enabled) swops chars  in the logged files. The data coming in is clean as you see it coming in. Somewhere in the file writing side things go wrong.  You can see in the screenshot that the timestamp (added by the extension itself and not the rs232 device) also got corrupted. This issue happens randomly. I had this issue on a Win10 laptop with VS code 1.81.1 (extension version v0.10.0), a Manjaro (arch linux) laptop with VS code 1.81.1 (extension version v0.10.0) and another Win10 laptop with VS code 1.82.0 (extension version v0.10.0) and a windows 7 laptop with an older version of VS code.  
[B_10s_8855_COM9_2023_08_23.09.44.53.459.txt](https://github.com/microsoft/vscode-serial-monitor/files/12584574/B_10s_8855_COM9_2023_08_23.09.44.53.459.txt)
![image](https://github.com/microsoft/vscode-serial-monitor/assets/79470643/c67f6ee4-2d56-4887-b8cf-69e529224d72)

**Comment by gcampbell-msft** [comment]
@Chris-DV What version of the extension are you using?

**Comment by Chris-DV** [comment]
Hi @gcampbell-msft, we are using the v0.10.0 on the laptops. I see another user also had this issue #110 (moran991231 posted on 2023-06-05). Please let me know if you need more info :)

**Comment by gcampbell-msft** [comment]
@Chris-DV Could you switch to the pre-release version and see if the issue still reproduces? There is an _attempted_ fix in the pre-release channel.
