### ISSUE TITLE
Chinese display garbled characters

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-serial-monitor#13]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/102402151/173724599-8d5c15b9-d8b1-422c-a565-ad88eafbf9e8.png">

device manager：
<img width="356" alt="image" src="https://user-images.githubusercontent.com/102402151/173724641-87425428-fcc7-44ba-99b9-0f1b9caa64b4.png">

**Comment by gcampbell-msft** [comment]
Hi @xiaguangbo! I'm looking into this issue, and it'd be helpful to me if you could provide text of what the characters are that are missing as well, so that I can copy them and test with them, thanks!

**Comment by xiaguangbo** [comment]
@gcampbell-msft This is Chinese in device manager：
```
USB 串行设备 (COM5)
...
蓝牙链接上的标准串行 (COM8)
....
```

**Comment by gcampbell-msft** [comment]
@xiaguangbo Thanks! I believe we may have been narrowing down where this issue is, we will let you know when we have a fix, though we don't have a timeline for when that will occur.

**Comment by 1184197761** [comment]
![image](https://user-images.githubusercontent.com/56498478/184316401-cb2ad35c-ff0a-41c2-8235-7dc1ebd3abee.png)
中文字体随机出现乱码，希望可以解决一下

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking here #47
