### ISSUE TITLE
Setting for specifying the line ending when sending text via TCP

### ISSUE THREAD

**Issue by UCSIG** [microsoft/vscode-serial-monitor#130]
Type: Feature Request

# Setting for specifying the line ending when sending text via TCP

First of all, thanks for the useful extension!
When using TCP as the monitor mode, it would be super useful if there were an option to specify the line ending that is appended to the text when pressing `Send as text`, similar to the option available in serial monitor mode. The application receiving data via TCP expects a `\n` newline character as the terminating character when parsing commands.

Cheers

**Comment by gcampbell-msft** [comment]
@UCSIG Thanks for the recommendation! I have placed it on the backlog and we will get to it as our soonest availability based on our overall workload.

**Comment by rdavies-intel** [comment]
Was just about to enter the same request, this change would be really useful.
