### ISSUE TITLE
Serial port timestamps on both send and receive

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode-serial-monitor#135]
Type: Feature Request

Serial monitor details.

1) It would be nice to have timestamps on sent data (when sent message echoing is on) also.

Now, the echoing always write "---- Sent utf8 encoded message: " and then the data.

Instead I would like to see something like "12:10:30:722 <- " and then the data sent.

The timestamp, is that on the first byte or the last byte. Mostly for slower baud rates, it would be nice if the shown timestamp was set from detecting the first byte received and when sending set after last byte was sent.

That way, one could actually make use of the timestamps to measure response times.

**Comment by gcampbell-msft** [comment]
@iqapps Thanks for all of these suggestions, they seem very reasonable and make a lot of sense. I will place these on the backlog and we will continually assess where best they fit in with our workload.
