### ISSUE TITLE
Open an Additional Monitor Doesn't Work

### ISSUE THREAD

**Issue by orlyprofili** [microsoft/vscode-serial-monitor#136]
Type: Bug Report
Open an Additional Monitor Doesn't Work
- OS and Version: Macos 13.5.1
- VS Code Version: 1.82.2
- Serial Monitor Extension Version: v0.10.0
- Target embedded device: ARM-M
- Other extensions you installed (and if the issue persists after disabling them): unknown

Repro:
1. Press "Open an Additional Monitor". Nothing appears to happen.
2. Press two more times, and this error will show, suggesting instances were loaded, but the GUI is not showing a tab bar.

<img width="1188" alt="Screenshot 2023-09-26 at 10 27 54 PM" src="https://github.com/microsoft/vscode-serial-monitor/assets/18429800/cc4b7f0a-19ff-4110-b95c-75a3c9bd24a3">

**Comment by gcampbell-msft** [comment]
@orlyprofili Could you please screen record or take a screenshot of your entire VS Code screen when trying to use the "Open an additional monitor" feature? 

I've found that it can be very easy to not realize that the new monitor did in fact open. Please let me know and I'll work to help investigate.

**Comment by orlyprofili** [comment]
here you go.  Open vscode, clicking on "open an additional monitor" 3 times, see error.  

https://github.com/microsoft/vscode-serial-monitor/assets/18429800/f6360bf1-1c46-453f-bc59-08f248d84d71

**Comment by gcampbell-msft** [comment]
I just tested and this seems to work on  my machine. My guess is that it's opening but in a non-obvious location that maybe you previously put them in?

Either way, and easy way to tell, is to type the following into the command pallete

"View: Focus on Serial Monitor" and the following should come up and you can select which view you want to focus on:
![image](https://github.com/microsoft/vscode-serial-monitor/assets/86264750/5b1d9a00-4869-41cc-af99-cbe8a0a3fa05)

If the three views don't show up in the dropdown, then it is confirmed that you're right, something is wrong. 

Looking forward to hearing from you.

**Comment by orlyprofili** [comment]
thanks! this, and then right-click "reset view" did the trick, and it's persisting after relaunch of vscode

**Comment by gcampbell-msft** [comment]
@orlyprofili Great! I'm glad that fixed your issue.
