### ISSUE TITLE
Can the end of the line display its ASCII？

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-serial-monitor#14]
I can't see what value the different line endings actually are

<img width="447" alt="image" src="https://user-images.githubusercontent.com/102402151/173725149-8bf69913-8274-4822-ba32-07a41315bb88.png">

**Comment by xiaguangbo** [comment]
Does the watch pattern mean time stamp? I clicked with no response. What does the 'ab \n c' icon mean?

**Comment by gcampbell-msft** [comment]
The line endings are the following: LF = \n, CR = \r, CRLF = \r\n.

**Comment by xiaguangbo** [comment]
@gcampbell-msft It would be more intuitive if it displayed its ASCII to the right of 'LF'
like this：
```
LF       \n
CR      \r
CRLF  \r\n
```

'ab \n c' refers to the icon on the right side of the watch

**Comment by gcampbell-msft** [comment]
Ah! That is "autoscroll". Again in this instance, if you hover over the icon, it _should_ tell you that, if it isn't, please let us know. 

This allows your output to stay at the fresh input as input comes in.

**Comment by xiaguangbo** [comment]
@gcampbell-msft There is no hint on mouseover, so I can only guess.
info:
OS: Windows 11
VSCode: 1.68.0(user)

**Comment by gcampbell-msft** [comment]
@xiaguangbo Thanks for your suggestion! However, I wanted to update you that we likely won't be implementing this, as VSCode follows this same pattern of displaying "LF", "CR", "CRLF". 

Thanks again and please let us know if any other issues or ideas arise.
