### ISSUE TITLE
Shortcut to open the Serial Monitor extension

### ISSUE THREAD

**Issue by MicSG-dev** [microsoft/vscode-serial-monitor#141]
Resource Request.
I would like there to be a shortcut (command) to open the Serial Monitor extension panel in Visual Studio Code.

**Comment by gcampbell-msft** [comment]
There currently is default support for this, when you first open VS Code, the command `View: Focus on Serial Monitor View` should be available. 

Upon your confirmation that this command is present, we likely won't make any changes here, please let us know if this command works for you!

**Comment by MicSG-dev** [comment]
> There currently is default support for this, when you first open VS Code, the command `View: Focus on Serial Monitor View` should be available.
> 
> Upon your confirmation that this command is present, we likely won't make any changes here, please let us know if this command works for you!

Thanks! I hadn't seen this option. 👍
