### ISSUE TITLE
Unable to create new window

### ISSUE THREAD

**Issue by lscszh** [microsoft/vscode-serial-monitor#143]
Type: Bug Report

**Describe the bug**
- OS and Version:windows11
- VS Code Version: 1.83.1 (user setup)
- Serial Monitor Extension Version: v0.10.231005001
- Target embedded device:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
- Description: At first I installed the release version, after the installation was complete, I opened three Windows, and then I couldn't find a place to close it, so I forced vscode to close, and then I re-opened vscode and found that I couldn't open the window. Now click to open the second window will prompt "No serial monitors are available to start monitoring a port. Only 3 can be opened at one time.", Now I can't even open the second window using the preview version

**To Reproduce**
Impossible to reproduce

**Expected behavior**

**Code sample and logs**
- Code sample
- `launch.json`

**Screenshots**

![image](https://github.com/microsoft/vscode-serial-monitor/assets/96347269/5d519d30-45f2-474b-a753-25ecb3f64eae)

**Additional context**

**Comment by gcampbell-msft** [comment]
@lscszh This likely a dup of #136 , could you attempt the suggestions mentioned in that bug? Thanks

**Comment by lscszh** [comment]
@gcampbell-msft Thank you, I tried your method, and now I have successfully opened three Windows
![image](https://github.com/microsoft/vscode-serial-monitor/assets/96347269/97b38a3e-9d54-4be7-b986-ba6037f0e158)
