### ISSUE TITLE
Feature Request: Ability to transmit/receive to/from TCP/UDP ports

### ISSUE THREAD

**Issue by rendayigit** [microsoft/vscode-serial-monitor#15]
Type: Feature Request

I'm not sure if this request fits the focus of this extension but I believe having functionality such as transmitting to and receiving from network ports would be useful. In the port drop down we could have like a network selection which could bring up a ip:port textbox. This would disable the Baud Rate selection. And we could have the option to create such connections as a "Server" or a "Client"

**Comment by gcampbell-msft** [comment]
Hi @rendayigit! Thanks for your suggestions. However, while it's a great suggestion, this is likely out of the scope of what we have planned for the serial monitor extension. I'll close this item due to that reason. Thanks again!

**Comment by benmcmorran** [comment]
This feature was added in version 0.6.0 of the extension, which is now available in the VS Code Marketplace. Thanks again for your feedback!
