### ISSUE TITLE
Adding timestamp to log output

### ISSUE THREAD

**Issue by si-moon** [microsoft/vscode-serial-monitor#151]
It would be nice to have this feature! Especially for Windows there is no good serial monitor software available.

**Comment by gcampbell-msft** [comment]
Hi @si-moon, thanks for reaching out! Our Serial Monitor actually already supports this! 

 This button toggles the timestamp when monitoring.
<img width="125" alt="image" src="https://github.com/microsoft/vscode-serial-monitor/assets/86264750/db61e232-810c-41b9-b59c-828f18039f46">

Does using this feature meet your needs?
