### ISSUE TITLE
Platformio VSC IDE Monitor multiple serial/tcp ports at a time:

### ISSUE THREAD

**Issue by JJDS** [microsoft/vscode-serial-monitor#152]
I was using, normally, two serial ports.
After changing workspace, I only have one and trying to open the second one ( two times or more, because nothing happens ) I get the message:
~No serial monitors are available to start monitoring a port. Only 3 can be opened at one time.

What can I do to resume to, until now, normal behavior.

Thanks in advance

Joaquim Silva

**Comment by gcampbell-msft** [comment]
Could you try to use the command mentioned in this comment? https://github.com/microsoft/vscode-serial-monitor/issues/144#issuecomment-1766055678

This should fix your issues. Sometimes VS Code persists the windows even though they aren't visible in the view. Thank you!

**Comment by hongshui3000** [comment]
https://github.com/microsoft/vscode-serial-monitor/issues/147  
Check your terminal tab. The windows that will open later are under the terminal tab. You need to drag them to where you want them.

**Comment by JJDS** [comment]
Thanks all for taking time to answer my post.
Really still only one serial monitor window, on the terminal one
![serial_monitor](https://github.com/microsoft/vscode-serial-monitor/assets/5372111/6b2394f7-d45b-49cf-89ed-4f186e282277)
I trying a lot of things ( looking for the windows ) but not succeded.
TIA
Joaquim Silva

**Comment by JJDS** [comment]
The thing is that before two days ago, I was working perfectly with 2 serial monitor windows!

**Comment by gcampbell-msft** [comment]
Could you try two additional things to see if it fixes your issue? 

1. Run the `View: Reset View Locations`. See if this fixes your issue. 
2. If that doesn't work, could you attempt to disable the extension, re-open VS Code, and then re-enable the extension? 

I would hope that this fixes your issues. Please let me know if it doesn't. 

If you think adding some sort of command from our extension to provide a simple way to bring focus to visible extensions, please let me know by creating a new issue for that. Thanks!

**Comment by JJDS** [comment]
Dear Garret:

Thanks for your interest, in solving the issue.
I followed your suggestions but nothing changed.
I also stopped Malware.
I tried to uninstall Serial Monitor, but not succeeded because it is an Arduino dependency.
But I disable it as per your instructions.

I must tell that this happened after I tried to open a second serial monitor window, when the system was still reopening.
May be this can give you a clue.

Waiting and still trying

Best regards

Joaquim Silva

**Comment by JJDS** [comment]
I have refreshed the Extension applyed the command, but the only thing I get is three new attempts, and, after that the same error message: only three serial monitors allowed and only one serial monitor window. 
Thanks for your effort in help.
Do you think that, if I reinstall Platformio, this can help? I have not yet tryed it.

Thanks again.

JJDS

**Comment by gcampbell-msft** [comment]
@JJDS Could you, after opening all three Serial Monitors, attempt to open all other panes? For example, the terminal pane, etc. etc. Sometimes if you've moved the Serial Monitor pane to somewhere else it will open there again and isn't immediately obvious in the top screen.

**Comment by JJDS** [comment]
Solved!!!
Thanks a lot for your help.
Now I have the 3 serial monitor windows, if I wish so!
Thanks to you, and all of the people, that tried to help.
Best regards

JJDS
