### ISSUE TITLE
Why are there no  RTS DTR buttons?

### ISSUE THREAD

**Issue by mysteriousTreasure** [microsoft/vscode-serial-monitor#153]
[
![1](https://github.com/microsoft/vscode-serial-monitor/assets/95865062/7c9f9b73-a6f5-4236-9a50-cc972939b830)
](url)

**Comment by mysteriousTreasure** [comment]
This is only happening on my work computer, which runs Windows 10. Windows 11 at home can display the RTS button.
I have tried uninstalling, reinstalling, and switching various plug-in versions without seeing the buttons

**Comment by gcampbell-msft** [comment]
@mysteriousTreasure Interesting, thanks for the clarification!

Is this specific to any specific version of the extension? I ask because the most recent version of the extension doesn't have any changes to the RTS / DTR UI or implementation. 

Thanks!

**Comment by mysteriousTreasure** [comment]
Thank you, I really don't know why, can't solve, I can only use other serial assistant instead of it

**Comment by gcampbell-msft** [comment]
@mysteriousTreasure What version of the extensions does it not work on?

**Comment by gcampbell-msft** [comment]
Interesting, based on this comment: https://github.com/microsoft/vscode-serial-monitor/issues/153#issuecomment-1853127703, this is happening for all versions of this extension? Is that correct?
