### ISSUE TITLE
Unable to set baud rate to custom values beyond menu options

### ISSUE THREAD

**Issue by kaludjerovic** [microsoft/vscode-serial-monitor#155]
It's not possible to set a baud rate other than the options provided in the menu. For instance, a baud rate of 921600 cannot be configured.

**Comment by kaludjerovic** [comment]
Solved in #113 . Custom baud rate can be added to Baud rate dropdown menu in the extension settings.

**Comment by PedroLuisDionisioFraga** [comment]
I'm using version 0.12.0 and there are no more baud rate options available yet. Does anyone know if this has been resolved?

**Comment by gcampbell-msft** [comment]
@PedroLuisDionisioFraga What options are you claiming aren't available? 

You are able to modify the `vscode-serial-monitor.customBaudRates` to get other baud rates to use. Thanks!
