### ISSUE TITLE
No icon in activity bar

### ISSUE THREAD

**Issue by videopilot** [microsoft/vscode-serial-monitor#156]
If I drag Serial Monitor to my activity bar, it generally works as expected, but there is no icon for its button.

![image](https://github.com/microsoft/vscode-serial-monitor/assets/6528746/9a373663-0815-491b-83d8-10dce502fb5e)

**Comment by gcampbell-msft** [comment]
@videopilot Thanks for letting us know! I'll mark this as a bug and put it on our backlog. Thanks again!
