### ISSUE TITLE
Ability to send LF when in send as text mode

### ISSUE THREAD

**Issue by AlanMullett** [microsoft/vscode-serial-monitor#157]
Type: Feature Request

The serial device I am connecting to expects a dumb terminal to be connected which will send LF at the end of a command.

At the moment that means I have to drop into Send as Hex mode to send the 0x0A character and then go back into Send as Text.

Could you add LF to the options either:

- add Send LF to the options far right (where it currently has things like "Send Ctrl + C"
- add a "Send as Text with Linefeed" for the mode (but this is problematic)
- send a LF if I enter an empty message (so I can send the command using double return)
- something better you come up with :) 

Thank you.

**Comment by gcampbell-msft** [comment]
@AlanMullett What is stopping you from simply sending an empty string with the `Line Ending` option set to `LF`? We added the ability to send empty messages in 0.8.0, and with the line ending set to LF, you should be able to do what you are asking. 

Please let me know if this suggestion doesn't work, and how it's behaving if not. If it's not working, there may be a bug that I need to investigate. Thanks!

**Comment by benmcmorran** [comment]
If that doesn't work, implementing #92 (currently unimplemented) could also provide a solution as a more generalized version of the first suggestion ("add Send LF to the options far right").
