### ISSUE TITLE
Allow UTF-8 Characters to be Printed Correctly

### ISSUE THREAD

**Issue by MicSG-dev** [microsoft/vscode-serial-monitor#168]
Type: Feature Request

When a UTF-8 character like ã or ç is printed, it becomes a strange character: 

- ã becomes "Ã£";
- ç becomes "Ã§".

**Comment by gcampbell-msft** [comment]
Thanks. If you could provide a simple minimal repro, that would be very helpful and could help us look into it sooner rather than later. Thanks.

**Comment by MicSG-dev** [comment]
> Thanks. If you could provide a simple minimal repro, that would be very helpful and could help us look into it sooner rather than later. Thanks.

1. Upload the following sketch to an Arduino board:
```
void setup() {
  Serial.begin(115200);
}

void loop() {
  Serial.println("ã");
  Serial.println("ç");
  delay(1000);
}
```
2. Connect the VS Code Serial Monitor extension with the Arduino board and see the result:
```
---- Opened the serial port COM4 ----
Ã£
Ã§
```

**Comment by gcampbell-msft** [comment]
Thank you, I thought that it might be simple, but in my experience it's better to ask because sometimes there are minute differences that make a big impact. Thanks for providing that, I'll add it to our backlog.

**Comment by pkoevesdi** [comment]
I'd strongly second that request, I consider it a bug in 2024, compared to 1988. 😅

**Comment by gcampbell-msft** [comment]
@MicSG-dev @pkoevesdi Could you try installing this (after changing from .zip to .vsix) and see if it fixes your issue? 
[vscode-serial-monitor.zip](https://github.com/user-attachments/files/16250097/vscode-serial-monitor.zip)

**Comment by MicSG-dev** [comment]
@gcampbell-msft I did the following procedure:

1. I changed the extension of the downloaded file from .zip to .vsix;
2. I uninstalled the other version of the Serial Monitor extension;
3. I installed the extension via the .vsix file in VS Code;
4. I ran the same Arduino example described [above](https://github.com/microsoft/vscode-serial-monitor/issues/168#issuecomment-2012211790);

The result 😔:
![image](https://github.com/user-attachments/assets/e927a78a-7e0a-4516-ba84-0b99f6c05189)

It still keeps printing incorrectly.

**Comment by armandas** [comment]
@MicSG-dev It works for me. Also note that `ç` is printed correctly in your case, so maybe there's an issue with Arduino?

![image](https://github.com/user-attachments/assets/b96036ad-5cd7-4ab9-9516-fbba33aa79c4)

**Comment by MicSG-dev** [comment]
I redid the tests with Arduino boards of different models using a baudrate of 115200, and I think it's something on my ESP32 board:

Raspberry Pi Pico | ✅
-- | --
DOIT ESP32 DEVKIT V1 | ❌
Arduino Mega | ✅


Test OK with Arduino Mega and Raspberry Pi Pico:
![image](https://github.com/user-attachments/assets/f3c4a12b-fae2-4e75-a141-2bd5c1d4dc18)

Failed test with ESP32:
![image](https://github.com/user-attachments/assets/d94a54e5-225a-49f5-a9df-817192037ddc)

The strangest thing is that when using the same ESP32 board with other Serial Monitors, the result is successful:
- MobaXterm: 
![image](https://github.com/user-attachments/assets/2b134001-1932-44e0-8152-a4521294f40e)

- Arduino IDE 1.8.19: 
![image](https://github.com/user-attachments/assets/8f1af3a9-d0a2-49f5-b296-d15fea7ac135)

- Arduino IDE 2.3.2: 
![image](https://github.com/user-attachments/assets/5e8f85d6-e904-42d4-8c81-40dbd2c6dfba)

**Comment by MicSG-dev** [comment]
> Failed test with ESP32...

When using the hexadecimal output in the vscode-serial-monitor extension, both with the Raspberry Pi Pico that is successful, and the ESP32 that fails the tests, the same content is presented:
![image](https://github.com/user-attachments/assets/28027f30-67ae-4b3a-96dc-33bf897d40fa)

**Comment by armandas** [comment]
Out of interest, I tried my ESP32-S3-DevKitC-1 and it seems to work. All my tests are at 115200 baud.

**Comment by pkoevesdi** [comment]
> @MicSG-dev @pkoevesdi Could you try installing this (after changing from .zip to .vsix) and see if it fixes your issue? [vscode-serial-monitor.zip](https://github.com/user-attachments/files/16250097/vscode-serial-monitor.zip)

Yes, this works! Thank You!

**Comment by gcampbell-msft** [comment]
@MicSG-dev Thanks for testing, it sounds like in the general case my fix works and fixes the issue, but there is something additional about your case. This, unfortunately, will be harder for me to diagnose since I don't have your exact bug. I plan to mark this issue as `fixed-pending-release` once I merge the fix and put it into pre-release. It would help me if you create a new bug specifically for your issue where only the esp32 fails. This way, I can close this bug as fixed and handle your issue specifically by itself in a different GitHub issue. 

Thank you for your patience and cooperation.

**Comment by MicSG-dev** [comment]
@gcampbell-msft  Ok, I did what you requested. Issue: https://github.com/microsoft/vscode-serial-monitor/issues/190

**Comment by gcampbell-msft** [comment]
@MicSG-dev thank you, that helps me a lot and I appreciate your patience.
