### ISSUE TITLE
Checkbox shows in wrong position when copying received text

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-serial-monitor#17]
here is normal：
<img width="573" alt="image" src="https://user-images.githubusercontent.com/102402151/175026816-d0207277-af2d-4369-bfa2-57fa71b0552c.png">

The red vertical line is where my mouse is, but the blue check box didn't keep up
The actual copied content is correct, the blue checkbox shows it is wrong：
<img width="568" alt="image" src="https://user-images.githubusercontent.com/102402151/175027393-34534108-8b60-4caa-8150-5e6b56ca0ef6.png">

**Comment by xiaguangbo** [comment]
@gcampbell-msft This problem has been solved in the new version, does it need to be closed?

**Comment by gcampbell-msft** [comment]
Yes, not right now though. It's fixed in the pre-release version; we'll close it when it's fixed in the official release version. Thanks for confirming that it's fixed!
