### ISSUE TITLE
The title 'SERIAL MONITOR' is missing when the window is moved to the right side panel.

### ISSUE THREAD

**Issue by 95501380** [microsoft/vscode-serial-monitor#170]
![image](https://github.com/microsoft/vscode-serial-monitor/assets/82696233/5f65e1a5-dc17-45a7-8907-fb22336d65ec)
You can check the issue in this screenshot. 
Thanks.

**Comment by gcampbell-msft** [comment]
@95501380 Do you find that this issue also happens with other views such as the Terminal, Debug Console, or any other views?

**Comment by 95501380** [comment]
I think this is an icon issue.
'Terminal'/'Debug' tap show its own icons when I move these windows to the right panel whereas yours doesn't.
![image](https://github.com/microsoft/vscode-serial-monitor/assets/82696233/eb5537e6-f941-4d3e-96db-42ad0551a3f3)

**Comment by gcampbell-msft** [comment]
Perfect, I've got a fix in PR that fixes this, though our icon doesn't appear well in those contexts, it will show an icon so hopefully it will be less confusing. Maybe at some point in the future we can generate another icon that looks better in these contexts.

**Comment by zekageri** [comment]
Still doesnt show up, even in pre release version

![Image](https://github.com/user-attachments/assets/4a1168c3-9093-4329-aac5-5ffc4641750c)
