### ISSUE TITLE
no data in serial monitor using an Arduino on Apple M3 / Sonoma

### ISSUE THREAD

**Issue by JanMenssen** [microsoft/vscode-serial-monitor#171]
System 
- apple M3 / Sonoma

Using the serial port monitor and an arduino no data is visible to the serial monitor. No problems with uploading code to Arduino and receiving data from Arduino using the serial port (Matlab, python, C, all works). However the serial monitor does not work

Using another MacBook, Intel, with Ventura and the same Visual Code configuration works well.

Also serial monitors from other extensions works. Why does this standard not work ?

Kind regards - jan

**Comment by gcampbell-msft** [comment]
@JanMenssen, I'm curious if this is an external issue on our serialport dependency, could you use the command-line package to see if this is an issue with it? https://serialport.io/docs/7.x.x/guide-cli/#serialport-terminal

**Comment by JanMenssen** [comment]
@gcampbell-msft : Thank you for you comment and your suggestion

I am not happy with installing non-necessary programs on my computer. In my opinion every installed program may be a risk for malfunctioning on other programs (I am a software engineer for more than 30 years). Also the command npm which seems needed to install this serial port monitor is not recognized on my Mac ?
So I you can give me good reasons why you want installing the serial monitor you suggest, I will do install it. 

But as I mentioned earlier, serial communication with an Arduino works in a program I wrote in Matlab, it works in a program I wrote In Python and it works in a program I wrote in C. Also with another serial monitor in VS code (serial terminal from awsxxf) no problems.

And strange, on an old MacBook Pro 206 with Ventura no problems arise with VS code and the micosoft serial monitor. ??

Kind regards and again thank you for you suggestion

**Comment by JanMenssen** [comment]
Sorry, intention was not to close it

**Comment by JanMenssen** [comment]
I got a permission  error installing the serial port program  see below. Maybe this is related to the serial port program ??

jan@Jans-MacBook-Pro ~ % npm install -g @serialport/terminal
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/@serialport
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@serialport'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@serialport'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/@serialport'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/jan/.npm/_logs/2024-03-21T21_38_08_793Z-debug-0.log
jan@Jans-MacBook-Pro ~ %

**Comment by JanMenssen** [comment]
If I am using the serial monitor I am able to send bytes to the arduino, so it seems only the receiving part is not working

**Comment by gcampbell-msft** [comment]
@JanMenssen Thank you for being willing to try that out. I, like you, find it interesting that older version of Mac don't seem to have these issues. The intent of having you download that was to see if the issue is stemming from the serialport dependency. 

I haven't found anything that seems like this specific issue, but I wonder if it has something to do with an FDTI driver? https://github.com/serialport/node-serialport/issues/83

Without your specific version of Mac on hand, it's difficult to test this. Thank you for your patience.
