### ISSUE TITLE
Run commands via tasks (clear output, start monitoring, etc)

### ISSUE THREAD

**Issue by kyrlon** [microsoft/vscode-serial-monitor#176]
As previously noted in one SO [post](https://stackoverflow.com/q/72313487/13642249) and [another](https://stackoverflow.com/q/48510288/13642249), you should be able to call and execute an extension command with the `command` variable. However, nothing occurs when attempting to use the clear output command `"${command:vscode-serial-monitor.clearOutput}"` within my `task.json`.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Clear Serial",
            "type": "shell",
            "command": ["${command:vscode-serial-monitor.clearOutput}"],
            "presentation": {
                "reveal": "always",
                "panel": "shared",
            },
            "problemMatcher":[]
            // "group": "build"
        }
    ]
}
```
Here is an example of output that shows the serial port opening and closing and then being cleared from the command palette. 
![output](https://github.com/microsoft/vscode-serial-monitor/assets/25754667/85d097a6-e8e1-47e9-89bf-00fdb87935a6)

After that, there is an example where the task is attempted to be completed but nothing happens.
![output](https://github.com/microsoft/vscode-serial-monitor/assets/25754667/d8cdc0f4-ff70-40b5-9525-cb1714c4814e)

**Comment by gcampbell-msft** [comment]
Thanks for pointing this out @kyrlon. I have a PR up for this internally and we should have a fix out in the **pre-release channel** in the coming days. Thanks!

**Comment by gcampbell-msft** [comment]
@akancz This fix is already available in the pre-release channel, thanks!

**Comment by kyrlon** [comment]
Can confirm this works since version 0.12.0 - 2024-06-20 from the [Change Log](https://marketplace.visualstudio.com/items/ms-vscode.vscode-serial-monitor/changelog)
