### ISSUE TITLE
I want to use this plugin but when I enable it using the api code can't show that there is no this api

### ISSUE THREAD

**Issue by AERCR3** [microsoft/vscode-serial-monitor#181]
Can you do a video tutorial, I plan to make a custom serial port instruction plugin based on vsvode, I found this public API but things are not very smooth.
Can you do a video tutorial, I plan to make a custom serial port instruction plugin based on vsvode, I found this public API but things are not very smooth.

**Comment by gcampbell-msft** [comment]
@AERCR3 Are you asking for an instruction for how to interact with this extension? There is documentation here: https://learn.microsoft.com/en-us/cpp/embedded/serial-monitor?view=msvc-170&tabs=visual-studio. 

Or, are you referring to the Serial Monitor API? https://www.npmjs.com/package/@microsoft/vscode-serial-monitor-api?activeTab=code.
If so, then you should be able to see the api.d.ts file which will tell you the interface of the API. There is also a simple example in the README. Thanks!

**Comment by AERCR3** [comment]
Okay, no problem. Thank you for the link.
