### ISSUE TITLE
[icon] Change the Icon to be inline with physical labels used for Serial Ports

### ISSUE THREAD

**Issue by bprabhus** [microsoft/vscode-serial-monitor#184]
Type: Feature Request

Minor Suggestion to change the logo to be somewhat inline with physical labels used for Serial Ports

Existing:
- default
![default](https://github.com/microsoft/vscode-serial-monitor/assets/43651425/a85e4373-cfa3-477a-9d50-64876cb76814)

Suggested:
 - Change `> 010` to `> 101` to make it closer to `10101` labels on Serial Ports 
![logo](https://github.com/microsoft/vscode-serial-monitor/assets/43651425/d7947861-b11b-4bd1-a1a1-bdad37a80e5a)

**Comment by gcampbell-msft** [comment]
@bprabhus Thanks for the suggestion! However, we likely won't be able to get to this change as it would require image changes in multiple locations, and based on bandwidth, we wouldn't get to something like this is a long time. 

I'm going to close this issue, but if we ever decide to do something with our logo, we'll revisit this issue. Thanks!
