### ISSUE TITLE
API to receive data or send data by other extension.

### ISSUE THREAD

**Issue by huoyunjie** [microsoft/vscode-serial-monitor#186]
Type: Feature Request

I want to write an extension which can receive/send serial data, and don't want to show Serial Monitor UX.
I try to use the API of Serial Monitor, but I just can call open/close, can not find receive/send data API.
Can you provide more API? Or can you guide me how to create a similar extension as yours.

**Comment by gcampbell-msft** [comment]
@huoyunjie We don't have plans to extend the API to strictly send/receive data without the API. Thanks for your interest!
