### ISSUE TITLE
ada pengalaman seperti ini, eror ga ada tampilan apapun di serial monitor??

### ISSUE THREAD

**Issue by Febriyandi12** [microsoft/vscode-serial-monitor#192]
![Screenshot 2024-08-03 115821](https://github.com/user-attachments/assets/38722784-a0b6-447d-96ef-dc78b1fc96ee)
tidak keluar menu atau fitur apapun

**Comment by gcampbell-msft** [comment]
@Febriyandi12 What version of the extension are you using? I'm not able to reproduce this on the latest release on my machine. Thanks.

**Comment by Febriyandi12** [comment]
It turns out that if the screen is blank on the serial monitor, just right click the mouse and click again to display the serial monitor text
