### ISSUE TITLE
Select environment for ports

### ISSUE THREAD

**Issue by devingDev** [microsoft/vscode-serial-monitor#196]
Feature: 
I'm on Windows, using VSCode with Remote SSH extensions to a linux machine.

Now the device I want to connect to is not on the linux but on my local (windows) machine.
I wanted to see the serial connection stuff in vscode but sadly I can only see ports like "/dev/ttyS0" but no "COM4" and so on.
COM ports do show but only when I open a new vscode window and do not connect with the remote extension.

Is there a way to select which environment (remote , local) it looks for ports? This would be super useful, otherwise I constantly have to switch back and forth from other tools.
Have a good day!

**Comment by devingDev** [comment]
I just found out it is possible, by looking more through other issues searching for "environment" this time which i didn't before.
anyway found this https://github.com/microsoft/vscode-serial-monitor/issues/77
and apparently i have to put this:

```
    "remote.extensionKind": {
        "ms-vscode.vscode-serial-monitor": [
            "ui"
        ]
    }
```

Now it lists the COM ports!

**Comment by gcampbell-msft** [comment]
Glad you figured it out! Closing this issue.
