### ISSUE TITLE
Inconsistent timestamp between sending/local echo and receiving

### ISSUE THREAD

**Issue by daantimmer** [microsoft/vscode-serial-monitor#197]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.92.2
- Serial Monitor Extension Version: 0.12.0
- Target embedded device: STM32G4
- Other extensions you installed (and if the issue persists after disabling them): issue persists
- A clear and concise description of what the bug is.

There is an inconsistent timestamp between data received and the 'local echo print':
```
11:52:59:340 ->   30.000
11:52:59:356 ->   30.000
11:52:59:356 ->   30.000
11:52:59:373 ->   30.000
11:52:59:448 ---- Sent utf8 encoded message: "sfr 40;" ----
11:52:59:388 ->   30.000
11:52:59:388 ->   40.000
11:52:59:407 ->   40.000
11:52:59:420 ->   40.000
11:52:59:420 ->   40.000
11:52:59:436 ->   40.000
```
The target MCU sends data every 10ms. We send the command 'sfr 40;' which changes the data from '30.000' to '40.000'
Here you can see the 'Sent utf8 encoded message: "sfr 40;" message is printed with a timestamp of 448ms. But it is printed in between the timestamps 373ms and 388ms. It can also be observed that the observed change from 30 to 40 has a different timestamp then the local echo message. (Which is impossible unless our device has a way to look in to the future).

**To Reproduce**
1. Click on 'Toggle TimeStamp'
2. Enable 'Sent Message Echoing'
3. See error

**Expected behavior**
I would expect the timestamp of the local echo message to be the same as the timestamp of when it was actually sent.

**Code sample and logs**
none available

**Screenshots**
not required, see above text output

**Additional context**
none available

**Comment by gcampbell-msft** [comment]
@daantimmer Thanks for the issue! Definitely an interesting issue. Is this consistently repeatable on your board? 

If so, I may be able to reproduce with a board that I have an investigate. If it's not consistent, due to the nature of the bug, it may be difficult to reproduce and investigate. 

Any information would be great, thanks!

**Comment by daantimmer** [comment]
I'll try next Monday!

**Comment by daantimmer** [comment]
Also, what is your board? I might be able to whip up something that is shareable.
