### ISSUE TITLE
Feature Request: Ability to set number of bits, parity and stop bits

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-serial-monitor#2]
Type: Feature Request

In some cases, the number of bits (8 or 7), use parity (none, even, odd) and number of stop bits (1 or 2) is useful. Right now, it is not working but I am not sure why. These are common parameters for any serial port that should be user-configurable.

It is also not clear to me which settings it is using for bits/parity/stop-bits. I am assuming 8-N-1 (probably most common), and if not, please let us know.

**Comment by benmcmorran** [comment]
Thanks for the feedback! This extension is internally using the Node `serialport` library, which should [default to 8-N-1 as you suspected](https://github.com/serialport/bindings-cpp/blob/027529224ac4d064bb266a5d62aef5c4d612cc9f/lib/win32.ts#L50-L62). I'm marking this as a feature request and I expect we'll be able to work on it in the next release.

**Comment by gcampbell-msft** [comment]
This ability is now available in the **pre-release channel**! Availability in the regular release channel is pending an official release. 

Feel free to try it out!

**Comment by haneefdm** [comment]
Works, thanks
