### ISSUE TITLE
API for another extensions

### ISSUE THREAD

**Issue by SmejkalJakub** [microsoft/vscode-serial-monitor#20]
I am currently working on an extension for our development kit. Would it be possible to add some callable commands to use from my extension? 

I would like to make it easier for the user. 
The user would just click **Open Serial Monitor** in my extension and then it would set up **Baud rate**, **COM port**, and **Line ending** maybe even start monitoring.

**Comment by hongshui3000** [comment]
I hope there is an API to refresh the serial port list and get the serial port list

**Comment by gcampbell-msft** [comment]
The API is now available in the official release channel with version 0.8.0! Thanks for all of your feedback and we look forward to you all trying it out!
