### ISSUE TITLE
pollHotplug causes freezing every few seconds

### ISSUE THREAD

**Issue by paulhayes** [microsoft/vscode-serial-monitor#209]
Type: <b>Bug</b>

VSCode was freezing every few seconds, sometimes for as long as 1 second, while is extremely annoying while coding. Ran integrated extension profiler ( so glad that exists ) and discovered this extension was freezing when calling pollHotplug. No usb devices were plugged in, although my laptop has some internal usb devices like integrated webcam and touchpad. 

VSCode 1.94.2
Windows 10

Extension version: 0.13.1
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.25GB (27.84GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by gcampbell-msft** [comment]
When you noticed this, what was the state of the Serial Monitor extension? Was it looking for a reconnection, not used, etc?

**Comment by paulhayes** [comment]
I wasn't using it at the time.
