### ISSUE TITLE
VS Code Extension Host crashes when using this extension and other serial monitoring extension

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode-serial-monitor#21]
Type: Bug Report

**Describe the bug**
- OS and Version: MacOS 12.4
- VS Code Version: 1.68.1
- Serial Monitor Extension Version: v0.1.0
- Target embedded device: None
- Other extensions you installed (and if the issue persists after disabling them): Extension in development and issue stops without it
- A clear and concise description of what the bug is.

We are developing a device manager extension which also allows serial monitoring. When this extension is installed (e.g. its a hard dependency of `ms-vscode.vscode-embedded-tools`) our extension crashes the extension host when it activates.

I am guessing this is due to both extensions using the same native serial access package (does this extension use https://serialport.io/ ?) and that package is not handling the node contexts correctly to allow multiple instances to be loaded in the same process.

This is compounded by the `*` activation event in this extension which means it always loads the native module.

**To Reproduce**
1. Install this extension
2. Install another extension which uses https://serialport.io/ and activate it

**Expected behavior**

Extension host doesn't crash

**Additional context**

- Please use proper activation events and not `*`
- If using https://serialport.io/, please ensure the latest version of https://github.com/serialport/bindings-cpp/ is in use

cc @aleun

**Comment by gcampbell-msft** [comment]
@thegecko Thanks for letting us know! I'm looking into this now. I'll make sure to move away from using `*` as an activation event, which should mitigate the problem slightly, even if it still occurs when it is activated. 

As for the serial access package, we do use the node serialport, and I have confirmed that the bindings-cpp package is the latest version. I did some initial testing using your repro steps and other extensions, and I'm not sure that it is an issue with the serial port package. Both this extension and our vscode-arduino extension use that package, and I was able to activate both extensions alongside one another without the Extension Host crashing. 

Do you have any insight as to exactly when it crashes? 

Thanks for raising this and we'll work to get it fixed as soon as we can!

**Comment by thegecko** [comment]
Thanks for investigating this!

>  I have confirmed that the bindings-cpp package is the latest version

Awesome, I did some testing locally to confirm the 10.4 version handles node context correctly and it looks like it does.

> Both this extension and our vscode-arduino extension use that package, and I was able to activate both extensions alongside one another without the Extension Host crashing.

Interesting, I tried the same with our extension (activated 2 copies with different extension IDs) and also saw things working correctly.

I'm aware you may be stuck here as we are yet to release our extension for you to test with, let me do some more dissecting...

Out of interest, do you use any other native packages?

**Comment by gcampbell-msft** [comment]
Interesting, please let me know if you have any other findings!

The only native packages we use are `serialport` and [`usb`](https://www.npmjs.com/package//usb).

**Comment by thegecko** [comment]
> The only native packages we use are serialport and [usb](https://www.npmjs.com/package//usb).

Same with our extension!

Lol, I know a little bit about [node-usb](https://github.com/node-usb/node-usb). That could also be the culprit as it didn't play well with multiple versions loaded into the same process until [v2.4.0](https://github.com/node-usb/node-usb/releases/tag/v2.4.0).

Some more data on this crash, all is well when the extensions being loaded use the `*` activation event. I've found that explicit activations of one extension will crash the extension host.

**Comment by gcampbell-msft** [comment]
Interesting! 

Currently, our dependency on node-usb doesn't currently use 2.4.0, so you could be right about that being the culprit.

**Comment by thegecko** [comment]
> Currently, our dependency on node-usb doesn't currently use 2.4.0, so you could be right about that being the culprit.

Ahh, that's where I'd put my money.

Can I hep with updating the version?

**Comment by gcampbell-msft** [comment]
@thegecko There should be a pre-release version that now has the updated version of node-usb, as well as not using the `*` activation event. Let me know if that fixes this issue!

**Comment by thegecko** [comment]
@gcampbell-msft I've had a quick play with this prerelease and couldn't recreate the issue. Fingers-crossed, this has fixed the problem. Thanks
