### ISSUE TITLE
Adding another serial monitor fails

### ISSUE THREAD

**Issue by Luyi-2333** [microsoft/vscode-serial-monitor#212]
Type: Bug Report

**Describe the bug**
- OS and Version: Window_NT x64 10.0.22631
- VS Code Version: 1.95.1
- Serial Monitor Extension Version: 0.13.1
- Target embedded device: 
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
I clicked to add another serial monitor, but nothing happened. After clicking it three times, it showed : "No serial monitors are available to start monitoring a port. Only 3 can be opened at one time."

**Comment by gcampbell-msft** [comment]
@Luyi-2333 It's likely that it's being opened but it's not immediately visible. 

Could you run the `View: Focus on ...` command for the serial monitor views?

**Comment by Luyi-2333** [comment]
you are right, thank u

> [@Luyi-2333](https://github.com/Luyi-2333) It's likely that it's being opened but it's not immediately visible.
> 
> Could you run the `View: Focus on ...` command for the serial monitor views?
