### ISSUE TITLE
Send common control codes (eg. Ctrl-C Ctrl-D) etc.

### ISSUE THREAD

**Issue by TheWoodsy** [microsoft/vscode-serial-monitor#22]
Type: Send common control codes (eg. Ctrl-C Ctrl-D Ctrl-Z) etc.

The ability to send common control codes (eg. Ctrl-C Ctrl-D Ctrl-Z) etc.
Allow sending these through after clicking main output or input area.
Added bonus for allowing commonly used escapes like 'Shift-~ + .' to break ssh would be awesome.

Currently have not found a way to send any control codes to a USB serial device with this extension which renders it entirely non-functional for getting into any Adafruit Circuitpython device's REPL.

Cheers

**Comment by thre3eye** [comment]
Hi guys, anything happening here? It's been a while and this is not very useful for IoT without being able to send Ctrl+ . Thanks.

**Comment by gcampbell-msft** [comment]
@thre3eye Yes! We are actively working on this and making progress.

We hope to update you soon when it's in pre-release,

**Comment by benmcmorran** [comment]
Support for sending common control codes is now available in the pre-release channel. In this version there is a limited hardcoded set of supported control codes, but it's also possible to send arbitrary codes by entering their hex values and using the new "Send as Hex" feature.

![image](https://user-images.githubusercontent.com/6981284/218820304-c6f20903-c5da-427b-8afd-0cd908e6733a.png)

To switch to pre-release, simply click the pre-release icon in the VS Code Marketplace.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6981284/218820744-33d3e054-7d41-42d6-80f3-8f1843d12f25.png">

**Comment by thre3eye** [comment]
Just had a quick look and the current implementation works.

In terms of usability, I still prefer Putty - i.e. no separate input/output fields and accepting CTRL, but I often use a Surface Go for microcontrollers and appreciate the tool integrated into VSCode with its tiny screen (Auto-reconnect is better than Putty btw)

Now I only wish I could collapse the controls (+ Open additional monitor, Mode, Port, Baud, etc ) to save that space, but guess that's subject for another issue.

Thanks for the work!

**Comment by gcampbell-msft** [comment]
@thre3eye Thanks for the feedback!

In regards to collapsing the controls, that may be something that we can consider if it gets enough support, could you create a feature request in a separate issue?

**Comment by thre3eye** [comment]
> @thre3eye Thanks for the feedback!
> 
> In regards to collapsing the controls, that may be something that we can consider if it gets enough support, could you create a feature request in a separate issue?

Just did: https://github.com/microsoft/vscode-serial-monitor/issues/76

Thanks again :)

**Comment by gcampbell-msft** [comment]
This support is now available in the official release channel with version 0.8.0! Thank you for all of your feedback and we look forward to you trying it out!
