### ISSUE TITLE
visible delays in presenting serial data

### ISSUE THREAD

**Issue by crackwitz** [microsoft/vscode-serial-monitor#23]
Type: Bug Report

**Describe the bug**

Delays between pieces of a line are visible and noticeable. Putty doesn't appear to do that but HTerm behaves similarly (but a lot quicker).

The sketch does *not* send separate pieces at that point so I'd assume it's some buffering either in Arduino, the OS/driver, or in the applications.

**Metadata**
- OS and Version: Win 10, 21H2 I believe
- VS Code Version: it ought to be up to date
- Serial Monitor Extension Version: current non-pre-release
- Target embedded device: Arduino Nano
- Other extensions you installed (and if the issue persists after disabling them): `alefragnani.Bookmarks bmd.stm32-for-vscode cschlosser.doxdocgen donjayamanne.python-environment-manager eamodio.gitlens esbenp.prettier-vscode espressif.esp-idf-extension GitHub.copilot GitHub.vscode-pull-request-github GrapeCity.gc-excelviewer jeff-hykin.better-cpp-syntax josetr.cmake-language-support-vscode marus25.cortex-debug mhutchie.git-graph ms-dotnettools.csharp ms-dotnettools.vscode-dotnet-runtime ms-python.python ms-python.vscode-pylance ms-toolsai.jupyter ms-toolsai.jupyter-keymap ms-toolsai.jupyter-renderers ms-vscode-remote.remote-containers ms-vscode-remote.remote-ssh ms-vscode-remote.remote-ssh-edit ms-vscode-remote.remote-wsl ms-vscode.cmake-tools ms-vscode.cpptools ms-vscode.cpptools-extension-pack ms-vscode.cpptools-themes ms-vscode.vscode-serial-monitor ms-vsliveshare.vsliveshare ms-vsliveshare.vsliveshare-audio twxs.cmake VisualStudioExptTeam.intellicode-api-usage-examples VisualStudioExptTeam.vscodeintellicode vsciot-vscode.vscode-arduino wholroyd.jinja` (that's everything, and I have no clue if any of them interfere)

**To Reproduce**
1. print a line per second, make it ~70 bytes long
2. monitor

**Expected behavior**
that a line of moderate length appear in its entirety, or as quickly as the data arrives. 70 bytes at 115200 baud is ~6 milliseconds, which is imperceptible. even if there's just a 1-byte buffer, that shouldn't matter if there's no serious delay between moving buffers.

**Screenshots**

- this extension:
https://user-images.githubusercontent.com/7065108/177398365-506d9774-6ad3-42db-8310-63193dbea4aa.mp4
- putty for comparison:
https://user-images.githubusercontent.com/7065108/177398386-0efd7e5e-4762-4a7b-b4cf-5067db6c820f.mp4
- Hterm for comparison:
https://user-images.githubusercontent.com/7065108/177404762-e46e74c7-5064-4c65-81f8-efc429bdf314.mp4

**Comment by gcampbell-msft** [comment]
@crackwitz My apologies for forgetting to update you on the status of this bug, there should be an improvement in the pre-release channel, please feel free to try that out!

We also plan to do an official release soon
