### ISSUE TITLE
Feature Request: Delay between characters

### ISSUE THREAD

**Issue by ahnaftahmid39** [microsoft/vscode-serial-monitor#24]
**Type: Feature Request**

I was using this extension with my stm32f446 with usart protocol. One thing that would be useful is to introduce a delay between characters that being sent. Without this delay, sometimes one or two characters goes missing. 
Example: I compared this with a serial terminal called cutecom where character delay can be configured. The program on my microcontroller was about simply sending back the character it receives. Here are the results:

**Without delay:** 
![Without delay vscode](https://user-images.githubusercontent.com/25487803/178511380-573b805c-32bf-43bb-942a-3797423094e2.png)
![Without delay cutecom](https://user-images.githubusercontent.com/25487803/178511644-c961d50b-65f0-4a0a-94a6-518bdae8167f.png)

**With 1ms delay:**
![With delay cutecom](https://user-images.githubusercontent.com/25487803/178511747-b17cfe0b-0352-4535-845f-ff062e36cd5b.png)

**Comment by gcampbell-msft** [comment]
@ahnaftahmid39 To confirm, the program that you are running simply echos the data that it received from the port? Meaning that a simple repro test would be having the embedded program echo what it receives, start monitoring, and send it data such as "Hello World"?

If the above is the case, I wasn't able to reproduce this with the boards that I have at my disposal, if you could send us the exact program and board information, we may be able to investigate further! Let us know if there are additional ways we can help/investigate. For now, marking this with an "enhancement" label.

**Comment by ahnaftahmid39** [comment]
@gcampbell-msft yes, It is simply a program to echo what it receives using usart. My board: nucleo-f446re. Code snippet: 
Whenever I send character from pc it creates an interrupt and handles with this handler:
```c
  void UART2_IRQHandler() {
    while (!(USART2->SR & (1 << 5)));  // wait for RXNE bit to set
    uint8_t data = USART2->DR;  // Read the data. This clears the RXNE also
    USART2->DR = data; // load the data into DR register
    while (!(USART2->SR & (1 << 6)));  // Wait for TC to SET.. This indicates that the data has been transmitted
  }
  ```
My guess is waiting for the RXNE (receiver not empty) and TC (transmission completed) bits is why I need 1ms of delay. 
A working project is here: [bare-metal-i2c](https://github.com/ahnaftahmid39/bare-metal-i2c/blob/main/main.c) 
Just skip the I2C and BMP related codes to test.

**Comment by gcampbell-msft** [comment]
Hi @ahnaftahmid39, sorry for the delay. Could you install this vsix and let me know if it possibly fixes the issue? 

You'll want to download it and then rename it to .vsix and install it in VSCode.

[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/9294603/vscode-serial-monitor.zip)

**Comment by ahnaftahmid39** [comment]
@gcampbell-msft It didn't work due my bad code. 
This is the previous code for handling sending a character:
```c
void UART2_SendChar(uint8_t c) {
	USART2->DR = c; // load the data into DR register
	while (!(USART2->SR & (1 << 6)));  // Wait for TC to RESET.. This indicates that the data has been transmitted
}
```

With this code it works now:
```c
void UART2_SendChar(uint8_t c) {
	while (!(USART2->SR & (1 << 7)));  // Wait for TXE to RESET... check if transfer line is empty or not
	USART2->DR = c; // load the data into DR register
}
```

I apologize for wasting your valuable time.

**Comment by gcampbell-msft** [comment]
@ahnaftahmid39 Great, no need to apologize at all, I'm glad you got it working!

Please continue to use the Serial Monitor and let us know if there's anything you need help with. 👍
