### ISSUE TITLE
Feature Request: Configurable run on Host or the remote SSH server

### ISSUE THREAD

**Issue by H-H-bin** [microsoft/vscode-serial-monitor#25]
Type: Feature Request

|Cloud server(Linux)| <-----ssh-------> | Local PC (Win10)| <------USB-------> | embedded device|

In our team, we are using the VS Code SSH remote development on a cloud server, and sync the built images back to local (Win10 PC) then debugging them,
so, the Serial Monitor run on the cloud server is not possible, instead, we hope this extension can be
chooses to be run on local instead of the remote when we install the extension.
Is that possible?

Thanks,
Bing

**Comment by benmcmorran** [comment]
Thanks for your feedback! I've updated the extension to prefer running locally. You can try out the changes by switching to the pre-release channel (see image) and ensuring you are running version 0.7.221213001 or later. If for some reason you need to force the extension to run remotely, use the `remote.extensionKind` setting in `settings.json`. Let me know if you run into any issues.

![image](https://user-images.githubusercontent.com/6981284/207413324-6e30fa32-112c-4ec1-9fe0-8f51664dddfb.png)

**Comment by H-H-bin** [comment]
Thanks @benmcmorran , It works!!!!

![image](https://user-images.githubusercontent.com/3911177/208084871-0db46eba-a758-48b6-98ba-dc2c5f797a96.png)
