### ISSUE TITLE
The usb serial port cannot be automatically refreshed after plugging and unplugging

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#26]
Serial com 2 exists in the system, but cannot be seen in the expansion
![image](https://user-images.githubusercontent.com/25566498/179889776-bad5524b-bef4-464b-8264-4959dc3507e9.png)
![image](https://user-images.githubusercontent.com/25566498/179890188-27f374ab-d4c5-4e5f-b7da-3a4b34ab80af.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Could you provide some information about the board that you are using? I'm not able to reproduce this as all of the boards I have are automatically being detected on plug-in. If you provide some info about the board we can attempt to repro. Thanks for the feedback!

**Comment by hongshui3000** [comment]
I use an FT232 usb to uart adapter board, there is an ft232 chip on the pcb, the uart and the uart of the chip I debug are connected to each other (my chip is on another pcb board)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thanks for that information! I'm still having trouble reproducing, I've got a configuration with multiple boards plugged in, and it seems to be recognizing them any time I unplug and re-plug. 

However, I can imagine that if you unplug and then immediately reconnect the device in very quick succession, the library might not be handling the back-to-back events correctly. However, I'll continue to investigate

**Comment by hongshui3000** [comment]
>However, I can imagine that if you unplug and then immediately reconnect the device in very quick succession, the library might not be handling the back-to-back events correctly. 

It is true that the serial port cannot be recognized in the case of this kind of fast plugging and unplugging. When there are multiple serial ports

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thanks! I believe we may have been narrowing down where this issue is, we will let you know when we have a fix, though we don't have a timeline for when that will occur.

**Comment by hongshui3000** [comment]
works，thanks

**Comment by hongshui3000** [comment]
The node usb update solved my issue, thanks a lot.@gcampbell-msft
