### ISSUE TITLE
DTR and RTS signal Setting Request

### ISSUE THREAD

**Issue by shuaihuGao** [microsoft/vscode-serial-monitor#27]
Type: Feature Request

DTR and RTS signals are used in many embedded fields. It is hoped that the status of default DTR and RTS signals can be set in the configuration.

**Comment by Josverl** [comment]
especially needed for the windows port as the default state the RTS with the serialport library will but most espxx boards into bootloader mode on restart
being able to toggle DTR/RTS while connected would be a bonus.

ref: https://github.com/pycom/pymakr-vsc/issues/212
