### ISSUE TITLE
Open two serial ports at the same time

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#28]
I need to open two serial ports at the same time to monitor two related devices. 
Currently only one serial port can be opened and data can be sent to one serial port at the same time

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thanks for the suggestion! However, we currently don't have an estimate on if/when we will be able to support the monitoring of multiple ports. 

One way that you could accomplish this though, is to open two instances of VSCode, this will allow you to monitor the two devices at the same time. 

Thanks!
