### ISSUE TITLE
Czech special characters displayed wrong

### ISSUE THREAD

**Issue by SmejkalJakub** [microsoft/vscode-serial-monitor#29]
While testing your extension we ran into an issue with special symbols in PORT select box

The intended text is ```Komunikační port (COM1)``` but we got ```Komunika?n? port (COM1)``` so I suppose there is some issue with Czech special characters.

**Comment by gcampbell-msft** [comment]
@SmejkalJakub Thanks for pointing this out! We will work to get this corrected.

**Comment by SmejkalJakub** [comment]
@gcampbell-msft sorry for the delay, here is the image that you requested.

The intended text is: ```Standardní sériová linka pomocí protokolu Bluetooth (COM3)```

![image](https://user-images.githubusercontent.com/18617626/183250680-97666381-ed39-4f3f-9eea-923cee074e5b.png)

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking here #47
