### ISSUE TITLE
Should remember Baud rate and Line-ending settings (all settings)

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-serial-monitor#3]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows
- VS Code Version: 1.66.2
- Serial Monitor Extension Version: v0.1.0
- Target embedded device: Infineon PSoC6
- Other extensions you installed (and if the issue persists after disabling them): Cortex-Debug (my extension)
- A clear and concise description of what the bug is.

Between invocations of VSCode, it should remember all the settings. Currently, baud rate and line-ending are not remembered. These should be really per workspace settings too. Maybe same issue exists with other settings.

**To Reproduce**
1. Set `Baud rate` to anything other than 300, and `Line Ending` to `CRLF`
2. Optionally try to use the monitor for some embedded use, if you wish.
3. Exit VSCode, restart, examine the `SERIAL MONITOR` tab.
4. Settings are not what was there before. Reverted back to 300 and None

**Expected behavior**
Should remember all settings on a workspace/folder basis

**Comment by benmcmorran** [comment]
Thanks for the feedback! There are a few different ways to persist this data in VS Code. To clarify, assuming we added a `vscode-serial-monitor.defaultBaudRate` (and similar) setting for workspace and global settings.json files, does this make sense to you as the search order for defaults?

1. Workspace settings.json. This means the user has explicitly set a default for the workspace.
2. Global settings.json. This means the user has explicitly set a global default.
3. Most recently selected value from [workspace state](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.workspaceState). This means the user has not explicitly set a default, but has used the Serial Monitor before in this workspace.
4. Most recently selected value from [global state](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalState). This means the user has not explicitly set a default or used the Serial Monitor before in this workspace, but they have used the Serial Monitor before.
5. Some hardcoded default fallback value.

**Comment by haneefdm** [comment]
> To clarify, assuming we added a vscode-serial-monitor.defaultBaudRate (and similar) 

Yes, exactly.

As to the search order, you are right again. Except, I need to do a bit of research -- my own extension as an example to see what VSCode actually does when I change a setting programmatically. It has been a while since I looked at that code. Quick look at the code, it does the following to change the setting

```typescript
        const config = vscode.workspace.getConfiguration('cortex-debug');
        vscode.commands.executeCommand('setContext', `cortex-debug:some-setting`, newVal);
        try {
            config.update('some-setting', newVal); 
        ....
```
For `config.update(...)` a target is not specified but the default target is a workspace and it just works across sessions. I don't remember the mechanics. I inherited some of this code but I don't know what or how VSCode resolves the `update` vs `get` across sessions.

But we also have to monitor for setting changes including changes done programmatically
```typescript
        vscode.workspace.onDidChangeConfiguration(this.settingsChanged.bind(this)),
```

All of the work to react setting change is actually done by the `settingsChanged` method and not at the point of updating a setting (programmatically or otherwise)

Maybe we are doing it all wrong but our extension was created a looong time ago, before workspaces existed. 

Note: We used the `WorkspaceConfiguration` API almost exclusively not global/workspace states

**Comment by benmcmorran** [comment]
Got it, thanks for confirming and providing all those examples! That should be plenty for us to address this issue.

**Comment by haneefdm** [comment]
Just one more thing. The `settingsChanged` is super generic. So we do the following
```typescript
    private settingsChanged(e: vscode.ConfigurationChangeEvent) {
        if (e.affectsConfiguration('cortex-debug.some-setting')) {
    ...
```
You may not have to be selective like we had to and assume everything changed.

**Comment by gcampbell-msft** [comment]
@haneefdm Support for remembering settings is now active in the **pre-release channel**! Currently there is no support for manual/explicit user settings in a settings.json, though that is likely coming, though persistance across sessions is supported!

**Comment by haneefdm** [comment]
Works
