### ISSUE TITLE
Add more cmd like behaviors

### ISSUE THREAD

**Issue by qwerty13** [microsoft/vscode-serial-monitor#30]
Hi
I am using this extension for the first time today, and at least it is better than arduino's extension serial monitor 😄
i suggest the creators to add some time booster features like we see in dos and command prompt and linux bashs;

for example in cmd we can press up arrow to fill send textBox the previous text we send, or if we mix send textBox with somthing like intellisense, it can detect and suggest about previous commands and arguments (like "send=0xa9b52b4e,salam")

Another feature can be highlighting similar words according to mouse-highlighted text in receive box.

at last, please add more configs for serial communication (and tooltip for the exists 😄)

**Comment by gcampbell-msft** [comment]
Hi @qwerty13, Thanks for your feedback! I'm happy to say that some of your suggestions are already implemented and available in pre-release (as some of them were bugs, i.e. the tooltips not existing). We plan to do a release either today or tomorrow for these to be in the official release channel!

**Comment by gcampbell-msft** [comment]
Closing this issue due to the majority of your requests (history and more config) are now released. Feel free to make specific feature requests in other issues!
