### ISSUE TITLE
Interpret escaped ANSI terminal codes

### ISSUE THREAD

**Issue by duddie** [microsoft/vscode-serial-monitor#31]
Type: Feature Request

ANSI Escaped terminal codes do not get interpreted. 
This should give colour output, instead it prints escaped codes

[0;32mI (0) sto_preset: Loading chunk data: 2000be74 00000004[0m

**Comment by hongshui3000** [comment]
similar requests :https://github.com/microsoft/vscode-serial-monitor/issues/4

**Comment by gcampbell-msft** [comment]
Closing as a duplicate of #4 and #11
