### ISSUE TITLE
Feature Request: automatic reconnect

### ISSUE THREAD

**Issue by NomiChirps** [microsoft/vscode-serial-monitor#33]
Type: Feature Request

Thank you for this nice extension :)

While developing for the Raspberry Pi Pico, I reflash and reset the board a lot, causing the serial connection to be lost. Currently to reestablish it with this extension, I have to go to the Port dropdown, select COM7 again each time, and hit Start Monitoring. It would be very nice, and save me some wrist strain, if this extension could remember that I had COM7 open and automatically reconnect as soon as it becomes available again.

**Comment by axel-lebourhis** [comment]
+1 this.
In my env, I can work remotely with embedded devices and sometime I need to shutdown the USB port (for a complete power reset) and I need to reselect the com port and start monitoring.

**Comment by benmcmorran** [comment]
This feature is added in version 0.6.0 of the extension, which is now available in the VS Code Marketplace. Thanks again for your feedback!
