### ISSUE TITLE
Ability to open multiple com ports in a single vs code window

### ISSUE THREAD

**Issue by axel-lebourhis** [microsoft/vscode-serial-monitor#34]
Type: Feature Request

Hi !

Would be nice to be able to open multiple com ports in a single window, could be a split or a different tab (or both).
For now I have to open multiple vs code window to do so, which is not really convenient.

Cheers !

**Comment by gcampbell-msft** [comment]
#28 Related issue. With two people having mentioned this I'll leave this one open for future triaging.

**Comment by bilboquet** [comment]
Hello,
I'd also really love to have this feature.

In many cases I have to monitor more than one serial port, often they are related to each others. So, an interleaved view code would be great, something like:
s1: msg from serial 1
s1: msg from serial 1
s2: msg from serial 2
s1: msg from serial 1
s2: msg from serial 2
s2: msg from serial 2
...
It might be an enhancement of the enhancement.
Anyway, great job.

**Comment by gcampbell-msft** [comment]
@bilboquet We now have support for opening multiple concurrent monitors at the same time in the pre-release channel!

**Comment by benmcmorran** [comment]
This functionality is now available in version 0.4.0 of the extension, which was released yesterday to the VS Code Marketplace.

**Comment by axel-lebourhis** [comment]
I just tried it, it awesome, thanks guys for this !
