### ISSUE TITLE
Additional baud rates or custom

### ISSUE THREAD

**Issue by ecarter-anduril** [microsoft/vscode-serial-monitor#35]
Type: Feature Request

Please add standard baud rates up to 921600bps or allow for a custom baud rate to be entered.

**Comment by gcampbell-msft** [comment]
Hi, @ecarter-anduril, thanks for the feedback! This is currently supported in the most recent release. There is a "Custom Baud Rates" Setting where you can input custom baud rates that you want to be used. Please let me know if you have any trouble using this feature!

Thanks

**Comment by gcampbell-msft** [comment]
dup #1
