### ISSUE TITLE
Characters such as 'é' in french alphabet and '%' are not displayed correctly

### ISSUE THREAD

**Issue by Aeldit** [microsoft/vscode-serial-monitor#36]
![Screenshot (4)_cr](https://user-images.githubusercontent.com/81476169/186448485-0b1f236a-9eaf-4b3a-a1bd-6615f9976e26.png)
The red thing is the serial monitor output is uspposed to be a '%', and the 'COM4 - ...' is supposed to be 'COM4- Périphérique série USB (COM4)'

**Comment by gcampbell-msft** [comment]
#13, #29 related.

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking here #47
