### ISSUE TITLE
Automatically clear log and enable monitoring by event?

### ISSUE THREAD

**Issue by jnz86** [microsoft/vscode-serial-monitor#37]
Via my debug script, I would like to prepare the debug session by:

- Triggering the serial port view / switch to be the active terminal
- Start monitoring
- Clear log

Is it possible to include an events or commands to do this?

**Comment by gcampbell-msft** [comment]
It is not currently possible, but we have it on the backlog and will be soon planning when we might be able to implement this feature. Thanks!

**Comment by benmcmorran** [comment]
Leaving a note that this work may be part of #20.

**Comment by gcampbell-msft** [comment]
@jnz86 The Serial Monitor API is now available in the official release channel with version 0.8.0!
