### ISSUE TITLE
Add cmd+k on MacOS to clear UART log.

### ISSUE THREAD

**Issue by zchen-ambiq** [microsoft/vscode-serial-monitor#38]
Type: Feature Request

**Comment by eos1d3** [comment]
I am also looking for this. Please!

**Comment by gcampbell-msft** [comment]
We have placed this as work that we will get done before our 0.11.0 release, which will come after our 0.10.0 release (coming soon). 

We will do this by exposing a command that you can use. Additionally, you could then create your own keybinding to call that command. Thanks!

**Comment by gcampbell-msft** [comment]
This is now available in pre-release!
