### ISSUE TITLE
Add millisecond part of timestamp 

### ISSUE THREAD

**Issue by zchen-ambiq** [microsoft/vscode-serial-monitor#39]
Type: Feature Request

**Comment by gcampbell-msft** [comment]
Thanks for the request, this will likely be fixed soon in the pre-release channel, as I agree that the millisecond part should be there.

**Comment by gcampbell-msft** [comment]
@zchen-ambiq This is now available in the pre-release channel.

**Comment by zchen-ambiq** [comment]
Perfect, thank you!

08:24:49 ->

From: Garrett Campbell ***@***.***>
Date: Friday, September 9, 2022 at 5:45 AM
To: microsoft/vscode-serial-monitor ***@***.***>
Cc: Zhongyi Chen ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/vscode-serial-monitor] Add millisecond part of timestamp (Issue #39)
External Sender: This email originated outside of Ambiq


@zchen-ambiq<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzchen-ambiq&data=05%7C01%7Czchen%40ambiq.com%7Cdcc45a44fc5048c870f108da92613a1e%7Ce36a02086b2e463aa7b26b0e68a1e82c%7C0%7C0%7C637983243544360206%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=adwUiG%2FSkRDWlqU4fFtRl3Y2m8yfsIs6ObSGqmiWmQQ%3D&reserved=0> This is now available in the pre-release channel.

**Comment by benmcmorran** [comment]
This functionality is now available in version 0.4.0 of the extension, which was released yesterday to the VS Code Marketplace.
