### ISSUE TITLE
Autoscroll wrong functionality

### ISSUE THREAD

**Issue by qwerty13** [microsoft/vscode-serial-monitor#40]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 Build 22000.918
- VS Code Version: 1.71.0
- Serial Monitor Extension Version: v0.3.0
- Description of bug: there is two bug, see reproduce below.

**To Reproduce**
First:
1. Open Serial monitor
2. Toggle autoscroll off
3. Clear output
4. Press start monitoring
5. After a while of receiving, it scrolls automatically to the last but it's icon indicates "off".

Second:
1. Open Serial monitor and Start monitoring to get data
2. Toggle autoscroll off and scroll manually up
3. After a while, scroll to the last down. serial monitor automatically turns on the autoscroll but it's icon indicates "off".

**Comment by gcampbell-msft** [comment]
@qwerty13 Thanks for the report! Is there any way that you could provide a gif/video of the functionality? This could help in diagnosing. 

In the meantime, I'll also add it to our backlog to investigate. Thanks for the report.

**Comment by gcampbell-msft** [comment]
Hi @qwerty13 , I took some time to investigate this and try to reproduce the bug. Unfortunately, I wasn't able to reproduce the issue so far. Any video or example of the issue would be very beneficial. 

Thanks!
