### ISSUE TITLE
Fail to open the serial port /dev/ttyUSB0. on Linux

### ISSUE THREAD

**Issue by Ines333** [microsoft/vscode-serial-monitor#41]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 20.04.04
- VS Code Version: 1.71.0
- Serial Monitor Extension Version: v0.3.0

**To Reproduce**
After I choose all the settings and click Start Monitoring, the message says "Fail to open the serial port /dev/ttyUSB0.". 
It seems it's due to the permission issue.

**Screenshots**
![fail](https://user-images.githubusercontent.com/72301128/191459052-7eb95e87-a314-4e6a-b2d4-6abc940b6e29.jpeg)

**Comment by gcampbell-msft** [comment]
@Ines333 Could you provide some more context about what you mean by "It seems it's due to the permission issue". What permission issue are you referencing? 

Are you currently monitoring or using this port in any other program?

Any insight could help us diagnose the issue. Thanks!

**Comment by Ines333** [comment]
I used to use minicom to connect my MCU board. But I have to execute it with `sudo`, or I'll get the same permission issue.

**Comment by robotdad** [comment]
Have you configured your udev rules for the device? Is your user a member of the dialout group?

**Comment by Ines333** [comment]
After I add my user to the dialout group, it connects successfully. Thanks so much for your help : )
