### ISSUE TITLE
Color support info in message

### ISSUE THREAD

**Issue by Ines333** [microsoft/vscode-serial-monitor#42]
Type: Bug Report

**Describe the bug**
- OS and Version: macOS Monterey 12.5.1
- VS Code Version: 1.71.2
- Serial Monitor Extension Version: v0.3.0

**To Reproduce**
The printed messages include some color support info `[0m`, which isn't expected to show.

**Screenshots**

![colorSupport](https://user-images.githubusercontent.com/72301128/191462064-33664170-9141-47c4-8b4d-d8be03b183a0.jpeg)

**Comment by gcampbell-msft** [comment]
#4

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking with #46
