### ISSUE TITLE
How to close serial port

### ISSUE THREAD

**Issue by szdanian** [microsoft/vscode-serial-monitor#43]
How to close the serial port after open a serial port in the terminal window ?

**Comment by gcampbell-msft** [comment]
@szdanian to close the serial port, please press the "Stop Monitoring" button. 

After pressing the "Start monitoring" button, it converts into the "Stop Monitoring" button.

**Comment by gcampbell-msft** [comment]
Closing as resolved, please re-open if you need more information or assistance!
