### ISSUE TITLE
Support for SGR portion of ASNI escape sequences

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-serial-monitor#46]
Type: Bug Report

Multiple people have posted issues requesting that ASNI characters be supported, primarily for color support. 

Some screenshots from the issues are here: 
![image](https://user-images.githubusercontent.com/86264750/193899151-39c9acdf-7f5a-4bfd-b0e8-0a0a1c6f19e5.png)
![image](https://user-images.githubusercontent.com/86264750/193899179-5c2f2947-3672-4d17-8d70-289e969fc9b6.png)

#4 #11 #42 #45 

Our team plans to investigate whether we can support this and/or fit it into our backlog as soon as we can.

**Comment by hongshui3000** [comment]
ANSI codes are supported, but it seems that colors are not supported in the latest version

**Comment by gcampbell-msft** [comment]
@paveldedourek-eaton, @Ines333, @Lykkeberg

Hi! We now have implemented support for these escape codes and it is available for testing out in the current pre-release version of the serial monitor.

Please feel free to test it out and let us know if it works for you!

**Comment by hongshui3000** [comment]
> 

![image](https://user-images.githubusercontent.com/25566498/205802245-d8c9f6aa-f28b-430c-bff0-707427dda886.png)

**Comment by hongshui3000** [comment]
>  Could you provide a screenshot or gif of a repro of the colors not working? They should be supported so it's possible there is a bug and a screenshot or video would be very helpful!

Sorry it was my own mistake, the colors were also able to display successfully
![image](https://user-images.githubusercontent.com/25566498/205805503-1ec618d3-0cc4-4b28-8a19-def99dac8a6d.png)

**Comment by Ines333** [comment]
Hi @gcampbell-msft , I just tried it, and it works great! Thanks for your effort : )

**Comment by Lykkeberg** [comment]
Hi CampbellThanks a million, this just works great. I have tested it today and it works just as expected.I’ll keep using it, and report any issues I might come across.One again, thanks for your effort, it is highly appropriated.Kind regardsThomas LykkebergDen 5. dec. 2022 kl. 15.04 skrev Garrett Campbell ***@***.***>:﻿
@paveldedourek-eaton, @Ines333, @Lykkeberg
Hi! We now have implemented support for these escape codes and it is available for testing out in the current pre-release version of the serial monitor.
Please feel free to test it out and let us know if it works for you!

**Comment by gcampbell-msft** [comment]
Terminal support is now officially available in v0.8.0. Please try it out and let us know! We're excited to see this now officially released.
