### ISSUE TITLE
Localization issues in port names

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-serial-monitor#47]
Type: Bug Report

Multiple people have reported issues with characters showing incorrectly due to localization issues. 

This is due to an issue in one of our dependencies (an external bug).

#36 #29 #13

External issues and PR's here: https://github.com/serialport/bindings-cpp/pull/63, https://github.com/serialport/node-serialport/issues/2502

**Comment by gcampbell-msft** [comment]
Hi all, this should be fixed in the most recent pre-release of the extension, please try it out and let us know!

Thanks.

@SmejkalJakub
@xiaguangbo
@Aeldit

**Comment by SmejkalJakub** [comment]
Czech special characters work great, thank you for the fix.

![image](https://user-images.githubusercontent.com/18617626/204319819-151459b3-e865-4859-840e-10f4432d3d63.png)

**Comment by benmcmorran** [comment]
This issue is fixed in version 0.6.0 of the extension, which is now available in the VS Code Marketplace. Thanks again for your feedback!
