### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by huahua0525** [microsoft/vscode-serial-monitor#48]
Hopes to add the functions of sending and receiving hexadecimal data.

**Comment by hongshui3000** [comment]
https://github.com/microsoft/vscode-serial-monitor/issues/5

**Comment by gcampbell-msft** [comment]
Closing this as a duplicate of #5. Thanks @huahua0525 and @hongshui3000 !

**Comment by gcampbell-msft** [comment]
Also, I'd like to add that we do have this work item in our backlog. We don't currently have an ETA, but we are currently working to understand where it fits with our other feature requests. Thanks!
