### ISSUE TITLE
Display hex output data directly

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#5]
In embedded debugging sometimes it is necessary to directly display and send raw binary data (hexadecimal data), hope to add it

Similar to this extension:https://github.com/imlinhanchao/vsc-serialport-helper
![image](https://user-images.githubusercontent.com/25566498/172746574-bd463d36-8c5f-4258-936d-a50166cb45cb.png)

**Comment by benmcmorran** [comment]
Thanks for linking to the example -- that will help a lot to design this feature correctly. Marking as a feature request.

**Comment by rtm7777** [comment]
I'd like to have this implemented as `toggle autoscroll` button, so when it active we see HEX data (and send input aslo accept only hex), when not - default ASCII

**Comment by snehara99** [comment]
We're working on sending raw data such as hex through the input bar currently!

**Comment by benmcmorran** [comment]
Support for _sending_ hex data is now available in the pre-release channel. To switch to pre-release, simply click the pre-release icon in the VS Code Marketplace.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6981284/218820744-33d3e054-7d41-42d6-80f3-8f1843d12f25.png">

The upcoming release won't yet support _viewing_ hex data in the output, so I'm renaming this issue to make it easier to track.

**Comment by itldg** [comment]
This suggestion is more practical

**Comment by Alireza-Samadi** [comment]
There is one other thing that needs to be added to serial monitor:

Microcontroller programmers usually send HEX numbers from the microcontroller to VS Code but Serial monitor can not show HEX codes. 

Please add a feature to change RX view from TEXT to HEX to show the HEX codes or tell me the way to do this if it can do it.
