### ISSUE TITLE
TCP support clarification

### ISSUE THREAD

**Issue by haneefdm** [microsoft/vscode-serial-monitor#50]
Type: Feature Request

First, you all have been very busy adding features!!! Thanks. This is me wanting some clarification. I see that you now have TCP port support but the release notes (changelog) indicate that SWO decoding is also supported. I am hoping that

* SWO decoding is an option on top of TCP. Technically, SWO can also come through a Serial/tty port for some gdb-servers.
* Above means that TCP port can be also be viewed RAW. This can be used for SEGGER RTT via JLink or OpenOCD
* I am assuming the TCP port is bi-directional
* If the TCP port is closed, will there be any retry attempts? Sometimes, it is an issue of timing and sometimes it is because the debug session ended and a new session started which will close the TCP port for a while

If all of the above is already taken care of then great. If not please consider them as feature requests.

**Comment by gcampbell-msft** [comment]
@haneefdm Thanks for the feedback! Answers to your points are below.

First, SWO decoding is in fact an option on top of TCP. You can find the SWO toggle button in the "Additional Settings" (Gear icon). This ties in to your second bullet point, and yes, the tcp port can be viewed raw. (I'd be curious to chat with your about the use case for SEGGER RTT and how that works).

Third bullet point: Yes, the TCP port is bi-directional in the sense that the "Send message" text box works for TCP port as well, so you should be able to send data to the port.

4th bullet point: Currently there is no implementation for retry attempts. However, we are in the midst of implementing this for Serial Ports, and it seems doable to implement a similar feature for TCP ports. 

I hope that I sufficiently answered all of your questions! We'd love for you to try out the features and let us know how it goes.
Thanks

**Comment by haneefdm** [comment]
Thanks for the response. RTT is like SWO on steroids and very popular. It is free to use both in FW and host tools. 

https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer/

![image](https://user-images.githubusercontent.com/41269583/201401953-c30e36c1-12dc-4379-9e7e-eb59b16b5bde.png)


To give you a brief summary.

SWO requires you to waste a pin whereas RTT runs on top of the regular SWD pins used for Debug. Advantage of SWO is that it can run independently of an SWD connection as at a pin level, it is just TX UART.

SEGGER provides its own set of GUI tools to connect/view RTT as well but people like to be tied into the VSCode debug experience instead of multiple windows floating around.

The SEGGER Gdb Server and OpenOCD have mechanisms to open one or more TCP ports. There can be up to 16 RTT channels (I think) and with OpenOCD, you can each channel gets to bind to a TCP port. It will look like any other TCP connection. With SEGGER gdb server, you are limited to one channel. There is no need for any decoding. We can treat them as just a console and people used as their preferred STDIN/STDOUT. I sometimes just use `netcat` to interact.

**Comment by gcampbell-msft** [comment]
@haneefdm Great! This is useful information. It sounds like in the context of VSCode (gdbserver and openocd), the tcp support already supports RTT!

**Comment by haneefdm** [comment]
Thanks. I am closing this issue since there is nothing outstanding here. Cleanup your queue :-)
