### ISSUE TITLE
cannot copy paste from the serial output

### ISSUE THREAD

**Issue by klaff** [microsoft/vscode-serial-monitor#51]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11
- VS Code Version: 1.73.1
- Serial Monitor Extension Version: v0.5.0
- Target embedded device:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. collect some serial port data
2. select text
3. use Ctrl-C to copy
4. use Ctrl-V into an editor window to attempt to paste

**Expected behavior**
text is copied and pasted

**Comment by gcampbell-msft** [comment]
Hi @klaff, could you provide a gif or video of the reproduction? I wasn't able to reproduce this issue on a similar machine and the same version. 

Thanks!

**Comment by klaff** [comment]
Hi @gcampbell-msft , here you go:

In other instances, it has pasted the previously copied item again instead of a blank line. Before recording this demo, I disabled all other extensions in vs_code, restarted vs_code, and grabbed fresh serial input.

![serial_copy_paste_bug](https://user-images.githubusercontent.com/6796478/204345968-ae506895-a049-459c-95d2-c539451028c3.gif)

**Comment by klaff** [comment]
The problem is observed if I paste to another application as well, or if I use keyboard shortcuts (I used right-click menu for the .gif so you could see what I'm doing).  Also tried just now to use the Clipboard History tool in Windows (which one has to enable with settings -> clipboard ..., and it also does not show the result of the copy operation.

**Comment by gcampbell-msft** [comment]
@klaff Have you noticed this issue when using the Ctrl-C command?

The issue in your screenshot is known and there is a bug with the vscode handling of webviews and the cut/copy/paste context menu commands, I believe: https://github.com/microsoft/vscode/issues/165679 (there are many other issues as well)

**Comment by klaff** [comment]
I would have sworn I tried both keyboard shortcuts and the right-click menu (I even wrote Ctrl-C explicitly in my issue post), but right now it is working if I use Ctrl-C for the copy operation, so the most logical assumption is that I only tried the non-working right-click menu for the copy operation and implicitly assumed equivalence of Ctrl-C and the right-click menu.

Thank you for the debug.

**Comment by gcampbell-msft** [comment]
@klaff Perfect! I'll close this bug in favor of tracking that issue on the vscode repository.
