### ISSUE TITLE
Configurable Autoscroll by default

### ISSUE THREAD

**Issue by bogus43** [microsoft/vscode-serial-monitor#52]
Type: Feature Request

I don't see an option in the settings to set autoscroll "on" as default when starting Serial Monitor (if I'm wrong and this option exists - please correct me). Now I have to toggle this option every time I start Serial Monitor. Is it possible to add option to make it configurable in settings that it will be "on" by default when launching Serial Monitor (like Line Ending, Stop Bits ect.)? Thanks.

**Comment by gcampbell-msft** [comment]
@bogus43 Thanks for the feedback! We agree with your suggestion, so we will be turning on `autoscroll` by default! 

Additionally, we will add `autoscroll` to the persistant setting across VSCode sessions, so you won't have to reselect it every time, regardless of your choice.

**Comment by benmcmorran** [comment]
Autoscroll is now enabled by default in the pre-release version of the extension, and the autoscroll setting will be persisted between sessions. You can switch to the pre-release version by clicking the pre-release icon in the extension marketplace. Let us know if you run into any issues, and thanks again for your feedback!

<img width="346" alt="image" src="https://user-images.githubusercontent.com/6981284/207109056-74434e6e-6d2c-48a4-8cee-36544e7f9846.png">

**Comment by bogus43** [comment]
Hello, sorry for very late reply, I checked that and this is what I had in mind. Thank You so much :).
I am closing this issue.
