### ISSUE TITLE
Sending Control And Escape Sequences

### ISSUE THREAD

**Issue by jimwheeler** [microsoft/vscode-serial-monitor#53]
May not be a bug but how can we send CTRL+.... and ESC + ..... sequences to serially connected devices?

**Comment by gcampbell-msft** [comment]
@jimwheeler Thanks for the feedback, this is currently a feature request here: #22. 

We are currently investigating supporting common control codes like Ctrl+C, Ctrl+V, etc. 

I'm curious, what are you interested in sending with ESC + ?

**Comment by benmcmorran** [comment]
Support for sending common control codes is now available in the pre-release channel. In this version there is a limited hardcoded set of supported control codes, but it's also possible to send arbitrary codes by entering their hex values and using the new "Send as Hex" feature.

![image](https://user-images.githubusercontent.com/6981284/218820304-c6f20903-c5da-427b-8afd-0cd908e6733a.png)

To switch to pre-release, simply click the pre-release icon in the VS Code Marketplace.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6981284/218820744-33d3e054-7d41-42d6-80f3-8f1843d12f25.png">

**Comment by gcampbell-msft** [comment]
@jimwheeler Thanks for your feedback, we're excited to say that this support is now in the official release channel with v0.8.0!
