### ISSUE TITLE
Not able to open serial port on Remote SSH connection

### ISSUE THREAD

**Issue by erikgrahn13** [microsoft/vscode-serial-monitor#56]
Type: Bug Report

**Describe the bug**
- OS and Version: Local OS = Windows 10, Remote machine OS:  Ubuntu 20.04
- VS Code Version: 1.74.2
- Serial Monitor Extension Version:  v0.7.221223001
- Target embedded device: Custom Android Device

I can find the device I would like to connect to in the Port list (/dev/ttyUSB0-FTDI). 
Baud rate: 115200
Line Endings: LF

When clicking start monitoring the following text is displayed in the output
**** Failed to open the serial port /dev/ttyUSB0 ****

I am able to connect to that device/port without any problem using minicom with the same Baud rate and line endings.
$ sudo minicom -D /dev/ttyUSB0

I can't find any more information in any of the output logs provided in Visual studio code regarding any interaction with the serial port or serial monitor extension. I don't see anything in the dmesg logs as well.

**Comment by gcampbell-msft** [comment]
@erikgrahn13 This is likely an issue with your udev rules, see @robotdad's suggestion in this issue: #41
