### ISSUE TITLE
Customize the output fontsize

### ISSUE THREAD

**Issue by JC6123** [microsoft/vscode-serial-monitor#57]
Type: Feature Request

Hi! Thanks for developing such a handy tool! 

It seems this plugin's output font size has been set equal to the `--vscode-editor-font-size`. However, since the output panel is often at the bottom side and is usually smaller than the editor, some may prefer smaller font size in the output panel to display more information.

Is it possible to provide an api to customize the font size of the output message? Much appreciated!

**Comment by gcampbell-msft** [comment]
This is related to the request for an api from issue #20, so we can track it along with that work. Thanks for the suggestion and feedback!

**Comment by gcampbell-msft** [comment]
This support is now available in the official release channel with v0.8.0
