### ISSUE TITLE
log file is automatically saved

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#6]
I hope to be able to configure the automatic save log file to facilitate the analysis of the log later

**Comment by pdk0826** [comment]
I need this also, hope it will be available soon

**Comment by gcampbell-msft** [comment]
Hi, @hongshui3000 @pdk0826 ! There is now support for choosing a log file destination, toggling whether logging to a file is enabled, and then, after logging, the ability to open your log file!

This capability is currently only available in the **pre-release** version. It will soon be available in the official release pipeline. Feel free to try out the pre-release!
