### ISSUE TITLE
Selectable Message Encoding - Allow spaces in input to visually separate bytes

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode-serial-monitor#61]
Type: Feature Request

Sending raw data such as hex or binary by selecting message encoding

From this issue: #5

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/217993591-2d9b7871-2482-4bf4-b2a0-cf019f70af76.png)
![image](https://user-images.githubusercontent.com/25566498/217993818-b74fbedf-d14c-48ff-928c-b170b2f85833.png)
Sending bin and hex extensions will die, I have not sent successfully here

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thank you so much for testing out the pre-release channel so quickly! This was very helpful and we will have a fix out soon. Thanks again! 👍

**Comment by benmcmorran** [comment]
The issue should be fixed in version 0.6.230210002, which is now available in the pre-release channel on the VS Code Marketplace.

**Comment by hongshui3000** [comment]
It has been able to work normally, 
but the sending limit of multiples of 2bytes and the input cannot be separated by spaces seem unreasonable

It's hard for me to tell how many bytes I wrote like this
![image](https://user-images.githubusercontent.com/25566498/218234866-43a73055-bd02-4ea2-acf7-ed7d2874019c.png)

![image](https://user-images.githubusercontent.com/25566498/218234809-04813acb-479d-4206-b6c4-3c177027485b.png)

**Comment by snehara99** [comment]
@hongshui3000 Thank you for taking a look at the pre-release again so quickly! We are currently working on addressing the readability issue which comes from not allowing spaces in the binary and hex encoded inputs. We're addressing that currently!

As for the sending limit of multiples of 2bytes, can you point me towards where you see that? You should be able to send multiples of 1 bytes.

**Comment by hongshui3000** [comment]
> 

I understand what you said, hex must occupy two digits, for example, 1 must be written as 01

**Comment by hongshui3000** [comment]
don't understand this description
![image](https://user-images.githubusercontent.com/25566498/218652371-564edb3c-6985-4a91-b8b2-74528cc42a6e.png)

**Comment by snehara99** [comment]
@hongshui3000 Thanks for pointing that out. The changelog is incorrect and we are correcting it now.

**Comment by snehara99** [comment]
@honshui3000 Spaces are now automatically injected into the hex and binary encoded text field separating bytes. You can test it out by updating to the latest version in the pre-release channel!

**Comment by hongshui3000** [comment]
> @honshui3000 Spaces are now automatically injected into the hex and binary encoded text field separating bytes. You can test it out by updating to the latest version in the pre-release channel!

I tried it and it works fine
