### ISSUE TITLE
 refresh Port list 

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#62]
Type: Feature Request

I wish the extension would provide a button to refresh the serial port.

current issue：
![image](https://user-images.githubusercontent.com/25566498/211706527-1ae04455-729b-4117-bb69-aabcbc11f01b.png)
![image](https://user-images.githubusercontent.com/25566498/211706695-a09c33bc-1aac-4e84-9994-b68dee1f9c09.png)
![image](https://user-images.githubusercontent.com/25566498/211706983-a5f528e2-45f3-497a-b44a-abd51382f23d.png)

Reference implementation:
https://github.com/imlinhanchao/vsc-serialport-helper/blob/master/src/SerialPort.js

```
class SerialPortProvider {
	constructor(context) {
		this._onDidChangeTreeData = new vscode.EventEmitter();
		this.refreshPort();
		this.ports = [];
		this.context = context;
	}

	get onDidChangeTreeData() {
		return this._onDidChangeTreeData.event
	}

	async refreshPort() {
		let ports = await SerialPort.search();
		let paths = this.ports.map(p => p.path);
		let portNew = ports.filter(p => paths.indexOf(p.path) < 0);
		paths = ports.map(p => p.path);
		this.ports = this.ports.filter(p => paths.indexOf(p.path) >= 0);
		this.ports = this.ports.concat(portNew.map(p => new SerialPortItem(p, this.context,
			vscode.TreeItemCollapsibleState.Collapsed, () => {
			this._onDidChangeTreeData.fire();
		})))
	}

	refresh() {
		this.refreshPort();
		this._onDidChangeTreeData.fire();
	}

	getTreeItem(element) {
		return element;
	}

	async getChildren(element) {
		if (!element) {
			return await this.getSerialPortList();
		} else {
			console.dir(element);
			return ['baudRate', 'dataBits', 'stopBits', 'parity', 'view_mode'].map(a => new SerialPortAttr(element, a, 
				vscode.TreeItemCollapsibleState.None, () => {
				this._onDidChangeTreeData.fire();
			}))
		}

	}

	async getSerialPortList() {
		return this.ports;
	}
}
```

**Comment by hongshui3000** [comment]
> @hongshui3000 Have you tried unplugging the device, waiting a second, and then plugging it back in?
> 
> I tried to reproduce your issue and wasn't able to, I was able to re-populate the list by doing this.

Even if I replug it, the extension cannot be recognized, but I can recognize it when I open another monitor. This problem can only appear on certain brands of usb serial ports, and it seems to be related to the usb driver. I think if there is a function that can refresh the list, it should solve all issues. This is how I solved the issue when I used another extension of (refresh list)

**Comment by hongshui3000** [comment]
![1673685432368](https://user-images.githubusercontent.com/25566498/212463803-093f1dc9-74e3-46fb-9235-0cbca32b271b.jpg)
Sometimes I can still find duplicate serial ports and I can't refresh

**Comment by gcampbell-msft** [comment]
@hongshui3000
A manual refresh button has been added in the most recent pre-release version! Please feel free to try it out and let us know if this fixes your issue.

**Comment by hongshui3000** [comment]
> @hongshui3000 A manual refresh button has been added in the most recent pre-release version! Please feel free to try it out and let us know if this fixes your issue.

yes ，it works well. thanks

**Comment by gcampbell-msft** [comment]
This is now available in the official release channel with version 0.8.0, closing the issue.
