### ISSUE TITLE
update list of serial ports

### ISSUE THREAD

**Issue by sodanetworks** [microsoft/vscode-serial-monitor#64]
While working on my microcontroller I plug and unplug it several times and a new serial port is generated in the dropdown list. It needs a button to refresh the list of available serial connections. I have to open a second serial port window in order to connect to my device. It would be much easier if the list can be refreshed by the user. Thanks.

![image](https://user-images.githubusercontent.com/11424745/212557602-57bf2bac-fc9f-4511-a334-9ab7e5509969.png)

**Comment by hongshui3000** [comment]
https://github.com/microsoft/vscode-serial-monitor/issues/62

**Comment by gcampbell-msft** [comment]
@hongshui3000 @sodanetworks 
A manual refresh button has been added in the most recent pre-release version! Please feel free to try it out and let us know if this fixes your issue.

**Comment by gcampbell-msft** [comment]
This is now fixed in the official release channel as well with version 0.8.0, so I'll close this issue!
