### ISSUE TITLE
Ability to send a text file

### ISSUE THREAD

**Issue by DESkomar** [microsoft/vscode-serial-monitor#7]
Type: Feature Request
I'd like to be able to send the text from a file over the serial port, line by  line.  I am developing an interface for a streaming device and currently have a sample file of various messages that the streaming device will send in different circumstances that I need to parse. I'd like to be able to send the file for testing rather than having to get the device into the various states that would send the different messages. i.e. I am manually feeding the data into the port to emulate the physical device (e.g. on com 3). My application is reading the data on another port (e.g. com 5). I'd like to be able to feed all that data into the com 3 port at once by specifying a file to open and send rather than having to manually copy in 100's of lines individually.

**Comment by heartacker** [comment]
great, we need this indeed

**Comment by gcampbell-msft** [comment]
We have placed this as work that we will do for v0.11.0, which will be after v0.10.0 (coming very soon!). We plan to create context menu entries that will integrate into VSCode files, that will allow you to send selected text, as well as full files.

**Comment by gcampbell-msft** [comment]
@heartacker, @DESkomar This feature is now available in the pre-release channel!

While actively monitoring a port, you can open a file in VS Code, right click in the editor, and then select `Send to Serial Monitor` and select one of the options!
![SendFile](https://github.com/microsoft/vscode-serial-monitor/assets/86264750/4a61d42f-9677-4d2f-ab2f-9f2ae0780433)
