### ISSUE TITLE
There seems to be something wrong with the api call example

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#70]
![image](https://user-images.githubusercontent.com/25566498/215307501-7e3677bf-e7ce-4e62-b394-93583eab7537.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Echoing Ben's comment, thanks for the good catch! We'll get a fix for the docs and publish again. Thanks!

**Comment by hongshui3000** [comment]
@gcampbell-msft 
By the way
listAvailablePorts The latest api is not yet available??
![image](https://user-images.githubusercontent.com/25566498/216022360-92a13d76-4be7-4b09-a71b-b1d1f6611ffa.png)

![image](https://user-images.githubusercontent.com/25566498/216021704-28d8a31c-75d2-470e-bf7a-f6b8f33325c7.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thanks for the heads up. 

This is currently expected as we have not merged this implementation yet. It is coming. 

I should note that while the API version is 0.x.x, we are not making any claims about stability. When we are confident about the format of the API we will notify you and update the version to 1.x.x. It's exciting to hear that you're trying it out!

**Comment by gcampbell-msft** [comment]
This issue is now fixed in the official release of the extension, v0.8.0. Closing this issue.
