### ISSUE TITLE
Support ANSI/VT100 Terminal mode

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#72]
Type: Feature Request

ANSI/VT100 Terminal is used in many embedded serial debugging. 
For example, the shell of zephyrrtos
https://docs.zephyrproject.org/latest/services/shell/index.html#shell
or
https://github.com/microsoft/vscode-serial-monitor/issues/53
https://github.com/microsoft/vscode-serial-monitor/issues/22

Hope to support simple ansi/vt100 terminal mode

**Comment by gcampbell-msft** [comment]
@hongshui3000 This is currently available in the pre-release channel! Please try it out, and we plan to do an official release in the next week or so.

**Comment by gcampbell-msft** [comment]
#46

**Comment by hongshui3000** [comment]
> #46

This is the output of the serial port to the expansion, 
but it seems that if it is a terminal mode expansion input to the serial port, some changes are also required, otherwise the terminal device will not be recognized

**Comment by gcampbell-msft** [comment]
@hongshui3000 I'm not sure I fully understand what it is that you're asking for. We use xterm.js for our terminal, which supports ANSI/VT100. 

Are you asking for the ability to send escape sequences to your board? If so, that feature is incoming, and will be in pre-release (and then release) in the coming days.

**Comment by hongshui3000** [comment]
> @hongshui3000 I'm not sure I fully understand what it is that you're asking for. We use xterm.js for our terminal, which supports ANSI/VT100.
> 
> Are you asking for the ability to send escape sequences to your board? If so, that feature is incoming, and will be in pre-release (and then release) in the coming days.

yes，Thanks Reply

**Comment by gcampbell-msft** [comment]
This is now supported in the official release of the extension with v0.8.0! Closing this issue.
