### ISSUE TITLE
Add a setting for a custom separator for the timestamp

### ISSUE THREAD

**Issue by Guy-BEANSPerformaceUK** [microsoft/vscode-serial-monitor#75]
Type: Feature Request

The timestamp feature is great, but it would be nice to customise what the separator is with a setting, saves editing the output log files before importing into excel etc. 

Example from this:
17:29:19:592 -> 4901.96,341,186,185,0,0,0,0
To this:
17:29:19:592,4901.96,341,186,185,0,0,0,0
Or whatever the user enters into the setting
17:29:19:592---4901.96,341,186,185,0,0,0,0

**Comment by benmcmorran** [comment]
Support for custom timestamp separators is now available in the pre-release channel. Use the new `vscode-serial-monitor.timestampSeparator` setting to specify a custom timestamp separator to be used to separate the timestamp from the content. The default value is still ` -> `. To switch to pre-release, simply click the pre-release icon in the VS Code Marketplace.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6981284/218820744-33d3e054-7d41-42d6-80f3-8f1843d12f25.png">

**Comment by gcampbell-msft** [comment]
This is now supported in the official release channel as well with version 0.8.0.
