### ISSUE TITLE
Can it be configured to ignore the extension's own sending echo

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#79]
Type: Feature Request

vscode-serial-monitor
![image](https://user-images.githubusercontent.com/25566498/219845286-a79a79cd-ebb4-443b-b3a1-51b052bb0f4d.png)
When using the mcu shell serial terminal to debug, the insertion of extended echo will make the display very messy

Other PC-side shell serial port monitoring
![image](https://user-images.githubusercontent.com/25566498/219845056-d18d1473-1e3e-4001-9948-65eb35d9de8b.png)

**Comment by NelsonDaniel** [comment]
+1 

For my use-case is nice to have the echo for debugging purposes, but I would prefer to suppress that afterwards.

**Comment by snehara99** [comment]
@hongshui3000 The option to turn off message echoing is now available in the newest version update in the pre-release channel. Feel free to try it out and let us know if you encounter any issues.
