### ISSUE TITLE
Escaped serial port name on Linux

### ISSUE THREAD

**Issue by imi415** [microsoft/vscode-serial-monitor#8]
Type: Bug Report

**Describe the bug**
- OS and Version: Arch Linux
- VS Code Version: 1.68.0
- Serial Monitor Extension Version: 0.1.0
- Target embedded device: N/A, UART bridge: CH340
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. Start and stop serial monitoring
2. The serial port name is displayed as `&#x2F;dev&#x2F;ttyUSB0`

**Expected behavior**

The serial port name should be displayed as `/dev/ttyUSB0`

**Screenshots**

![image](https://user-images.githubusercontent.com/10695162/172967653-b1c67529-31e0-4916-b794-76f00e90f016.png)

**Additional context**

**Comment by gcampbell-msft** [comment]
Thanks for reporting this! We'll look into this and get it fixed for the next release.

**Comment by gcampbell-msft** [comment]
@imi415 Thanks for your feedback! I wanted to let you know that we do not currently have a date in mind, but that we have a fix for this issue ready to ship in the next release.
