### ISSUE TITLE
Improper UI label colors in dark themes

### ISSUE THREAD

**Issue by tehKaiN** [microsoft/vscode-serial-monitor#81]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 10 22H2 19045.2604
- VS Code Version: 1.75.1
- Serial Monitor Extension Version: 0.8.0
- Target embedded device: Silabs USB-UART adapter, n/a
- Other extensions you installed (and if the issue persists after disabling them): n/a
- A clear and concise description of what the bug is: When selecting one of dark themes, e.g. Tomorrow Night Blue, the labels near Mode/Port/Baud/Line ending options are using wrong font color and are almost unreadable.

**To Reproduce**
1. Select Tomorrow Night Blue theme
2. Open the Serial Monitor tab
3. Try to read labels near options.

**Expected behavior**
Labels should be easily readable and have their font color contrasting with the background.

**Code sample and logs**
n/a

**Screenshots**
Note the black-on-blue labels.
![obraz](https://user-images.githubusercontent.com/16180344/220080278-37e989df-a4b9-407e-97ce-13498fe7cb81.png)

**Additional context**
n/a

**Comment by Eplankton** [comment]
> 谢谢你让我们注意到这一点， @tehKaiN !
> 
> 我们很快就会对预发布频道进行修复，希望能在明天之前完成，谢谢！

Same problem for me, sir. I'd like to see this to be fixed....just a small bug anyway.
![捕获](https://user-images.githubusercontent.com/86543401/221580404-a143d6c0-cfdd-48a2-8432-37017c0ee600.PNG)

**Comment by gcampbell-msft** [comment]
@Eplankton Thanks for confirming that there is an issue. We have released a fix in the most recent pre-release channel! Feel free to try it out there by navigating to the extension pane for the Serial Monitor and selecting, "Switch to pre-release". 

![image](https://user-images.githubusercontent.com/86264750/221583446-d29e9a4c-2243-4507-9ae8-947bed899852.png)

**Comment by Eplankton** [comment]
> @Eplankton Thanks for confirming that there is an issue. We have released a fix in the most recent pre-release channel! Feel free to try it out there by navigating to the extension pane for the Serial Monitor and selecting, "Switch to pre-release".
> 
> ![image](https://user-images.githubusercontent.com/86264750/221583446-d29e9a4c-2243-4507-9ae8-947bed899852.png)


Thanks for your and the team's efforts, finally we have an official extension for Serial Monitor (which is especially helpful for embedded software developers) , I wonder whether an official extension for memory viewer exists, for now I just use [https://github.com/mcu-debug/memview]() as an alternative.

**Comment by gcampbell-msft** [comment]
This should be fixed in v0.9.0. Thanks!
