### ISSUE TITLE
Send messages without pressing Enter or Submit

### ISSUE THREAD

**Issue by NelsonDaniel** [microsoft/vscode-serial-monitor#82]
Type: Feature Request

Scenario: 

I am building a Robot Car, and I need to send commands over serial connection using Bluetooth Classic. I would like to send single characters (commands) without the need to press ENTER. Without this feature, it becomes tiresome to have to press enter every time a command is typed.

I am able to achieve this behavior by default using Putty. However, I would prefer to use this extension since it is friendlier to setup and use than Putty.  Specially, since I plan to use this project for teaching high schoolers an intro to embedded development.

**Comment by hongshui3000** [comment]
I also have similar needs
![image](https://user-images.githubusercontent.com/25566498/220530213-edb5bf85-f0ac-47e7-88de-c4ea75e927a1.png)
This can meet my needs for debugging various types of devices

**Comment by hongshui3000** [comment]
Further UI interface suggestions(Mainly to simplify the UI)
![image](https://user-images.githubusercontent.com/25566498/222062411-f8adf5aa-f571-48f8-9443-332ddc327419.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000, just wanted to make a note that we did move DTR and RTS to the additional settings section, thanks for the suggestion!

**Comment by gcampbell-msft** [comment]
@hongshui3000 and @NelsonDaniel, we have now put into pre-release a "Terminal Mode" that we'd love your feedback on! It's very much a beta version, but we'd love to hear your feedback to know if it meets your needs or if it needs more work. Thanks!

**Comment by hongshui3000** [comment]
Terminal Mode All functions are good, a little suggestion
The right-click menu only has copy but no paste，It would be better if the right-click menu has a paste function, such as copy command from other places. While CTRL + V currently works with

**Comment by gcampbell-msft** [comment]
@hongshui3000 Great! This is a good suggestion, I'll open a separate issue to track it.

**Comment by mzq2306** [comment]
Terminal mode is very good, but there is a small bug, every time you enter the command, the terminal will be more than one line, I don't know whether it is plug-in problem, as follows:
![Snipaste_2023-04-25_20-54-11](https://user-images.githubusercontent.com/45752320/234282835-993f0e90-a509-4633-af5f-060313098282.png)

**Comment by mzq2306** [comment]
Also, I suggest adding a shortcut to the serial monitor to make it easier to use.

**Comment by gcampbell-msft** [comment]
@mzq2306 Thanks for your feedback! A couple of questions:

1. Could you give a little more information on exactly what's happening in the bug? Is it entering additional lines when you enter text? Or is it that it opens a new line when you hit "enter"? Any context would be great.
2. What keyboard shortcuts are you interested in? It would be great if you could create a new issue on this repo for that request.

Thanks!

**Comment by somethingwithelectronics** [comment]
Hello;

first of all thanks for the great extention and I really like the new terminal mode.
But I am observing a behavior which I am unsure about if it is intended like this.
It seems that the terminal does not react to "\r" or CR if it receives it from the serial port.

My application reacts to a backspace with
` "\r                                                " & "\rSTRING_MINUS_LAST_CHAR"`

which results in the following output 

test_string
# press backspace
test_string                                                test_strin

Best regards and thanks for your work

**Comment by gcampbell-msft** [comment]
@somethingwithelectronics Thanks for the feedback! Could you open a separate issue for your bug? Then I'll follow up with some questions on that issue, so that we can make sure it doesn't get lost inside of this bug, which will be closed when we release the terminal mode in an official version. 

Thanks!

**Comment by RodMe27** [comment]
Another enhance on the terminal is that when you search in the history of commands with up-arrow and down-arrow it puts the information on the same line 
![image](https://github.com/microsoft/vscode-serial-monitor/assets/77603164/bffb8fc4-9b77-4f2f-9093-d267dda9dc6d)

I would be nice to just replace the actual line

**Comment by RodMe27** [comment]
> Another enhance on the terminal is that when you search in the history of commands with up-arrow and down-arrow it puts the information on the same line ![image](https://user-images.githubusercontent.com/77603164/251611253-bffb8fc4-9b77-4f2f-9093-d267dda9dc6d.png)
> 
> I would be nice to just replace the actual line

Just a heads up, I switched to pre-release and this is fixed, the add new line after hitting enter is still present :)

**Comment by RodMe27** [comment]
I just installed it, and it is working simply fine. Do you want me to try some test cases? 
![image](https://github.com/microsoft/vscode-serial-monitor/assets/77603164/214048c0-db9b-4963-b226-11f94a3d5bf9)

**Comment by benmcmorran** [comment]
Closing. Terminal mode is included in version 0.10.0.
