### ISSUE TITLE
Not working in WSL furthermore

### ISSUE THREAD

**Issue by CeSiumUA** [microsoft/vscode-serial-monitor#84]
Type: Bug Report

Hi! Serial Monitor extension is not working in WSL anymore by some reason....
It only shows me serial ports from my host PC, but not that are attached to WSL instance.
I've used it successfully a few months ago, but after a fresh install, this problem appeared

- OS and Version: Windows 11, 22H2 (OS build 22621.1265)
- VS Code Version: 1.75.1
- Serial Monitor Extension Version: 0.8.0
- Target embedded device: STM32F411

**To Reproduce**
1. Connect to WSL through Visual Studio Code
2. Attach a USB device to WSL via `usbipd wsl attach`
3. Go to Serial Monitor tab, and it shows only devices that are connected to my PC, but not in WSL

**Comment by gcampbell-msft** [comment]
Hi @CeSiumUA!

Thanks for notifying us. This is likely the same issue as #77 . Could you try the solution suggested by @benmcmorran [here](https://github.com/microsoft/vscode-serial-monitor/issues/77#issuecomment-1433498853)?

Please let us know if this works for you!

**Comment by CeSiumUA** [comment]
Hi, @gcampbell-msft !
Sorry for such a long delay, I've tried the solution described in that issue, and it worked!
Thank you very much, and sorry for bothering with such a same issue :)
I've just didn't notice that such a same issue with provided solution already exists 😅

**Comment by Eplankton** [comment]
> Hi @CeSiumUA!
> 
> Thanks for notifying us. This is likely the same issue as #77 . Could you try the solution suggested by @benmcmorran [here](https://github.com/microsoft/vscode-serial-monitor/issues/77#issuecomment-1433498853)?
> 
> Please let us know if this works for you!

Sir, I have encountered exactly same problem, but after I added the code to `settings.json` in my WSL project folder and then reloaded my vscode in WSL, the serial monitor just disappear from my toolbar, what's happening

**Comment by Eplankton** [comment]
> > 你好  @CeSiumUA!  
> > 感谢您通知我们。 相同的问题  [  这可能是与#77  ](https://github.com/microsoft/vscode-serial-monitor/issues/77)。   你能试试建议的解决方案吗  @benmcmorran [在这里  ](https://github.com/microsoft/vscode-serial-monitor/issues/77#issuecomment-1433498853)？  
> > 请让我们知道这是否适合您！
> 
> 先生，我遇到了完全相同的问题，但是在我将代码添加到 `settings.json`在我的 WSL 项目文件夹中，然后在 WSL 中重新加载我的 vscode，串行监视器从我的工具栏中消失了，发生了什么

Never mind, I have fixed it myself, just install a wsl version of serial monitor again.

**Comment by Eplankton** [comment]
> > Hi @CeSiumUA!
> > Thanks for notifying us. This is likely the same issue as #77 . Could you try the solution suggested by @benmcmorran [here](https://github.com/microsoft/vscode-serial-monitor/issues/77#issuecomment-1433498853)?
> > Please let us know if this works for you!
> 
> Sir, I have encountered exactly same problem, but after I added the code to `settings.json` in my WSL project folder and then reloaded my vscode in WSL, the serial monitor just disappear from my toolbar, what's happening

Never mind, I have fixed it myself, just install a wsl version of serial monitor again.
