### ISSUE TITLE
Typo in Changelog

### ISSUE THREAD

**Issue by YDX-2147483647** [microsoft/vscode-serial-monitor#87]
[Changelog in Marketplace](https://marketplace.visualstudio.com/items/ms-vscode.vscode-serial-monitor/changelog):

> ## 0.8.0 - 2022-02-15
>
> ## 0.7.0 - 2022-12-05

I guess v0.8.0 was released in **2023** (not 2022), or did you achieve time travel? 😄

**Comment by gcampbell-msft** [comment]
Thanks for pointing that out! We'll get that fixed. Thanks!

**Comment by gcampbell-msft** [comment]
Fixed in v0.9.0. Thanks!
