### ISSUE TITLE
Text sent from Arduino via serial port is distorted if it contains non-Latin characters

### ISSUE THREAD

**Issue by yeremee** [microsoft/vscode-serial-monitor#88]
Type: Bug Report?

**Describe the bug**
- OS and Version: Windows 11 22H2
- VS Code Version: 1.76.2
- Serial Monitor Extension Version: 0.9.0
- Target embedded device: Arduino UNO
- Other extensions you installed (and if the issue persists after disabling them): VS Code Arduino
- Summary: Text sent from Arduino via serial port is distorted if it contains non-Latin characters

**To Reproduce**
The example of a sketch:
> ![2023-03-24_17-53-41 (3)](https://user-images.githubusercontent.com/25692333/227732437-88c14ed6-8380-4fa6-ae48-3db35a7bced8.png)

<details>
<summary>
This is what the output looks like in Arduino IDE:
</summary>

![2023-03-24_17-55-16 (2)](https://user-images.githubusercontent.com/25692333/227732438-0756ef84-5d91-454d-8204-90bed201ee43.png)
</details>

<details>
<summary>
This is what the output looks like in VS Code: 
</summary>

![2023-03-24_17-53-41 (2)](https://user-images.githubusercontent.com/25692333/227732435-a99e485f-169e-4a24-927a-0cd406d693f4.png)
</details>

What's the matter? Why is the text distorted? I didn't find any encoding settings for the extension.

**Comment by yeremee** [comment]
@gcampbell-msft 
Here it is: [test-project.zip](https://github.com/microsoft/vscode-serial-monitor/files/11092193/test-project.zip)

**Comment by yeremee** [comment]
@gcampbell-msft 
Partially fixed:
![2023-03-29_16-35-25](https://user-images.githubusercontent.com/25692333/228555669-ddc05596-7503-490e-82cb-9e5bf632753d.png)

**Comment by gcampbell-msft** [comment]
Closing this issue in favor of #90. This fix was released in v0.10.0
