### ISSUE TITLE
Cannot send JSON formatted string to target

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-serial-monitor#91]
**Describe the bug**
- VSCode about:
   ```
   Version: 1.76.2
   Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
   Date: 2023-03-14T17:57:21.103Z
   Electron: 19.1.11
   Chromium: 102.0.5005.196
   Node.js: 16.14.2
   V8: 10.2.154.26-electron.0
   OS: Linux x64 6.2.6-76060206-generic
   Sandboxed: No
   ```
- Serial Monitor Extension Version: v0.9.0
- Target embedded device: STM32L4R5
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**

1. Attempt to send, `Hello, World!`
2. VSCode reports, `---- Sent utf8 encoded message: "Hello, World!" ----`
3. Attempt to send, `{"req":"card.restore","delete":true,"connected":true}` to the target.
4. VSCode reports, `---- Sent utf8 encoded message: "" ----`

**Expected behavior**
I would expect the string to be sent as typed.

**Code sample and logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/2801887/229547686-74e3fcb3-b1a7-4562-b11c-c73cce06d1ed.png)

**Additional context**
N/A

**Comment by gcampbell-msft** [comment]
@zfields Thanks for the issue! I should mention that from my current investigation, it seems like the json message does get sent to the port, but the output of it is obviously incorrect. 

I'm still investigating. I will report back if/when I find more answers.

**Comment by gcampbell-msft** [comment]
@zfields Update, I've found the issue and resolved it. The fix is in pre-release now!
