### ISSUE TITLE
Enter the custom baud rate in the configuration box

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#93]
Type: Feature Request

Enter the custom baud rate in the configuration box
![1681719027283](https://user-images.githubusercontent.com/25566498/232424700-fabe3549-0196-48a7-83ac-076be07cfa9e.jpg)

At present, I need to write the following configuration in the setting configuration to change to a customized baud rate, which is not very convenient for some scenarios that need to temporarily change the baud rate
```
"vscode-serial-monitor.customBaudRates":[600000]
```
Other Tool References
![1681719461803](https://user-images.githubusercontent.com/25566498/232426450-ff0bf6ad-12eb-4ce0-a75d-49d1d40766a2.jpg)
![image](https://user-images.githubusercontent.com/25566498/232426666-ab6535ed-4825-48c6-9c08-725201d09c98.png)

**Comment by gcampbell-msft** [comment]
@hongshui3000 Thanks for the request! We'll track it here for community upvotes and we'll investigate to see where it might fit on our backlog! Thanks again!

**Comment by gcampbell-msft** [comment]
We will implement this, but in a slightly different way than requested. We will modify how the custom baud rates settings.json works, such that it simply adds the custom baud rates to the list, rather than replacing the default list. Thanks!

This will come in v0.11.0, which will come after v0.10.0 (coming very soon!).

**Comment by gcampbell-msft** [comment]
This is now fixed in pre-release! Please try it out and let me know if it works!

**Comment by hongshui3000** [comment]
work fine,thanks
